// ============================================================
// 国际化 (i18n) + 货币格式化 + 实时汇率
// ============================================================
import { useState, useEffect, useCallback, createContext, useContext } from "react";

// --- 翻译字典 ---
const DICT = {
  // === Header ===
  brandSub: { zh: "Cross-border P&L · Россия 2026", en: "Cross-border P&L · Russia 2026", ru: "Кросс-бордер P&L · Россия 2026" },
  brandTitle: { zh: "俄罗斯电商损益与现金流计算器", en: "Russia E-commerce P&L Calculator", ru: "Калькулятор P&L для маркетплейсов" },
  saveCloud: { zh: "保存数据", en: "Save", ru: "Сохранить" },
  saving: { zh: "保存中…", en: "Saving…", ru: "Сохранение…" },
  exportCSV: { zh: "导出 CSV", en: "Export CSV", ru: "Экспорт CSV" },
  exportHTML: { zh: "导出报告", en: "Export Report", ru: "Экспорт отчёта" },
  usageGuide: { zh: "使用说明", en: "Guide", ru: "Гид" },
  htmlReportTitle: { zh: "俄罗斯电商投资效益分析报告", en: "Russia E-commerce P&L Analysis Report", ru: "Отчёт P&L для маркетплейсов" },
  htmlGenDate: { zh: "报告生成日期", en: "Report Generated", ru: "Дата отчёта" },
  htmlSummary: { zh: "总览摘要", en: "Executive Summary", ru: "Сводка" },
  htmlProductDetail: { zh: "商品明细", en: "Product Details", ru: "Детали товаров" },
  htmlCashFlow: { zh: "月度现金流明细", en: "Monthly Cash Flow Detail", ru: "Помесячный кэш" },
  htmlDisclaimer: { zh: "本报告由星哈酷投资效益分析系统自动生成，仅供测算参考，最终申报请咨询当地会计师。", en: "This report was auto-generated by XingHaKu Investment Analytics. For estimation only — consult a local accountant for filings.", ru: "Отчёт сгенерирован XingHaKu. Только для оценки — обратитесь к бухгалтеру." },
  htmlBreakEven: { zh: "回本月份", en: "Break-even Month", ru: "Месяц окупаемости" },
  htmlNoBreakEven: { zh: "预测期内未回本", en: "No break-even in forecast", ru: "Не окупается в прогнозе" },
  htmlTaxScheme: { zh: "税制方案", en: "Tax Scheme", ru: "Налоговый режим" },
  htmlExchangeRate: { zh: "汇率", en: "Exchange Rate", ru: "Курс" },
  htmlForecastPeriod: { zh: "预测期", en: "Forecast Period", ru: "Период прогноза" },
  resetSample: { zh: "重置样例", en: "Reset", ru: "Сброс" },
  saved: { zh: "✓ 已保存", en: "✓ Saved", ru: "✓ Сохранено" },
  saveFail: { zh: "保存失败", en: "Save failed", ru: "Ошибка сохранения" },
  loadedLocal: { zh: "已加载本地数据", en: "Local data loaded", ru: "Данные загружены" },
  shareLink: { zh: "分享链接", en: "Share Link", ru: "Поделиться" },
  shareCopied: { zh: "✓ 分享链接已复制到剪贴板", en: "✓ Share link copied to clipboard", ru: "✓ Ссылка скопирована" },
  shareFail: { zh: "生成分享链接失败", en: "Share link failed", ru: "Ошибка создания ссылки" },
  shareUploading: { zh: "⏳ 正在上传...", en: "⏳ Uploading...", ru: "⏳ Загрузка..." },
  loadedShare: { zh: "✓ 已从分享链接加载数据", en: "✓ Loaded from shared link", ru: "✓ Загружено из ссылки" },
  shareLoadFail: { zh: "分享链接数据加载失败", en: "Failed to load shared data", ru: "Ошибка загрузки из ссылки" },

  // === Tabs ===
  tabDashboard: { zh: "总览仪表盘", en: "Dashboard", ru: "Обзор" },
  tabProducts: { zh: "商品明细", en: "Products", ru: "Товары" },
  tabSchedule: { zh: "销售排期", en: "Sales Schedule", ru: "График продаж" },
  tabProjection: { zh: "现金流预测", en: "Cash Flow", ru: "Денежный поток" },
  tabSettings: { zh: "参数与税制", en: "Settings & Tax", ru: "Настройки" },
  tabHelp: { zh: "税制说明", en: "Tax Guide", ru: "Налоговый гид" },
  tabGlossary: { zh: "术语词典", en: "Glossary", ru: "Глоссарий" },

  // === Login ===
  loginTitle: { zh: "损益计算器", en: "P&L Calculator", ru: "Калькулятор P&L" },
  loginLabel: { zh: "访问密码", en: "Access Password", ru: "Пароль доступа" },
  loginPlaceholder: { zh: "请输入密码", en: "Enter password", ru: "Введите пароль" },
  loginButton: { zh: "进入系统", en: "Enter", ru: "Войти" },
  loginError: { zh: "密码错误，请重试", en: "Wrong password", ru: "Неверный пароль" },
  loginFooter: { zh: "星哈酷 · 投资效益分析工具", en: "XingHaKu · Investment Analytics", ru: "XingHaKu · Аналитика инвестиций" },

  // === Dashboard Metrics ===
  totalRevenue: { zh: "总营收", en: "Total Revenue", ru: "Общая выручка" },
  totalInvestment: { zh: "总投资", en: "Total Investment", ru: "Инвестиции" },
  russiaCollections: { zh: "俄罗斯回款", en: "Russia Collections", ru: "Поступления из РФ" },
  cashNetProfit: { zh: "商品经营利润", en: "Net Profit", ru: "Чистая прибыль" },
  projNetProfit: { zh: "预测利润", en: "Projected Profit", ru: "Прогноз прибыли" },
  endingCash: { zh: "最后账上还剩现金", en: "Ending Cash After Partner Payout", ru: "Остаток после выплаты партнеру" },
  projMonthsRange: { zh: "预测 {n} 个月", en: "{n}-month forecast", ru: "Прогноз {n} мес." },
  roiLabel: { zh: "回报率（ROI/投入产出）", en: "ROI", ru: "ROI" },
  netMargin: { zh: "利润率（净利率）", en: "Net Margin", ru: "Маржа" },
  bookNetProfit: { zh: "税务账面利润", en: "Book Net Profit", ru: "Бух. прибыль" },

  // === Dashboard Cards ===
  cumCashTitle: { zh: "累积现金流", en: "Cumulative Cash Flow", ru: "Накопленный кэш" },
  cumCashKicker: { zh: "Cumulative Cash", en: "Cumulative Cash", ru: "Кумулятивный кэш" },
  investorTitle: { zh: "投资人关注", en: "Investor Metrics", ru: "Метрики инвестора" },
  investorKicker: { zh: "Investor Metrics", en: "Investor Metrics", ru: "Инвестор" },
  initialOutflow: { zh: "M0 先付出去的钱", en: "Initial Outflow", ru: "Начальные вложения" },
  maxDrawdown: { zh: "最缺钱的时候", en: "Max Drawdown", ru: "Макс. просадка" },
  finalCash: { zh: "最后账上还剩现金", en: "Final Cash After Partner Payout", ru: "Итоговый кэш после выплаты партнеру" },
  avgMonthly: { zh: "月均回款（仅参考）", en: "Avg Monthly Revenue", ru: "Сред. месяц. выручка" },
  peakMonthly: { zh: "旺季峰值回款", en: "Peak Monthly Revenue", ru: "Пиковая мес. выручка" },
  monthlyPnL: { zh: "本月经营利润分布", en: "Monthly P&L", ru: "Помесячная прибыль" },
  monthlyPnLKicker: { zh: "Monthly P&L", en: "Monthly P&L", ru: "Помесячно" },

  // === Break Even ===
  breakEvenMsg: { zh: "第 {n} 个月回本（达成盈亏平衡）", en: "Break even in month {n}", ru: "Окупаемость за {n} мес." },
  noBreakEven: { zh: "预测期内未回本，可调整销售排期或延长预测期", en: "No break-even within forecast period", ru: "Не окупается в прогнозном периоде" },

  // === Cost Structure ===
  costStructure: { zh: "成本结构", en: "Cost Structure", ru: "Структура затрат" },
  costKicker: { zh: "Cost Structure", en: "Cost Structure", ru: "Затраты" },
  costProcure: { zh: "供应商报价/预估采购成本", en: "Procurement", ru: "Закупка" },
  costPlatformFee: { zh: "平台综合扣费", en: "Platform Burden", ru: "Расходы площадки" },
  costWarehouse: { zh: "海外仓", en: "Warehouse", ru: "Склад" },
  costMgmt: { zh: "管理费", en: "Management", ru: "Управление" },
  costTax: { zh: "税", en: "Tax", ru: "Налоги" },
  costOneTime: { zh: "一次性费用", en: "One-time Costs", ru: "Разовые расходы" },
  costNetProfit: { zh: "扣启动费后利润", en: "Net Profit", ru: "Чистая прибыль" },

  // === Tax Structure ===
  taxStructure: { zh: "税务结构", en: "Tax Breakdown", ru: "Структура налогов" },
  preTaxProfit: { zh: "税前利润", en: "Pre-tax Profit", ru: "Прибыль до налогов" },
  totalTax: { zh: "总税额", en: "Total Tax", ru: "Общий налог" },
  effectiveRate: { zh: "实际税负", en: "Effective Rate", ru: "Эффект. ставка" },

  // === Product Ranking ===
  rankingTitle: { zh: "商品盈利排行（按回报率）", en: "Product Ranking (by ROI)", ru: "Рейтинг товаров (ROI)" },
  rankingKicker: { zh: "Profitability Ranking", en: "Profitability Ranking", ru: "Рейтинг" },

  // === Products Tab ===
  productsTitle: { zh: "商品明细", en: "Product Details", ru: "Детали товаров" },
  productCount: { zh: "{n} 个产品", en: "{n} SKUs", ru: "{n} SKU" },
  productsHint: { zh: "点击行展开编辑。供应商报价/预估采购价、报关申报价、售价、平台综合扣费、海外仓费和管理费都按“上架销售单位”填写：6只装按整套，L12按整套12件，壶杯套装按整套；当前报价是测算假设，正式报价后需替换。", en: "Click a row to edit. Costs, list price, platform burden, overseas warehouse fee and management fee are per sellable listing unit, e.g. a 6-pack or 12-piece set, not per individual cup.", ru: "Нажмите на строку для редактирования. Цена и расходы указаны за продаваемую единицу/набор, не за отдельный стакан." },
  clearAll: { zh: "清空", en: "Clear", ru: "Очистить" },
  addProduct: { zh: "添加商品", en: "Add Product", ru: "Добавить" },
  productId: { zh: "产品ID", en: "Product ID", ru: "ID товара" },
  costCny: { zh: "供应商报价/预估采购价（¥/销售单位）", en: "Cost ¥/unit", ru: "Себест. ¥/ед." },
  qty: { zh: "数量（销售单位）", en: "Qty (sellable units)", ru: "Кол-во (ед. продажи)" },
  listPrice: { zh: "售价（₽/销售单位）", en: "List (₽/unit)", ru: "Цена (₽/ед.)" },
  platformFee: { zh: "平台综合扣费（₽/销售单位）", en: "Platform Burden (₽/unit)", ru: "Расходы площадки (₽/ед.)" },
  warehouseFee: { zh: "海外仓费（₽/销售单位）", en: "Overseas WH (₽/unit)", ru: "Склад (₽/ед.)" },
  mgmtFee: { zh: "管理费（₽/销售单位）", en: "Mgmt (₽/unit)", ru: "Упр. (₽/ед.)" },
  investment: { zh: "总投资", en: "Investment", ru: "Инвестиция" },
  revenue: { zh: "总营收", en: "Revenue", ru: "Выручка" },
  tax: { zh: "税额", en: "Tax", ru: "Налог" },
  netProfitCol: { zh: "利润金额（₽）", en: "Profit", ru: "Прибыль" },
  roi: { zh: "回报率（ROI）", en: "ROI", ru: "ROI" },
  action: { zh: "操作", en: "Action", ru: "Действие" },
  deleteBtn: { zh: "删除", en: "Delete", ru: "Удалить" },

  // === Schedule Tab ===
  scheduleTitle: { zh: "销售排期 · 淡旺季销量计划", en: "Sales Schedule · Seasonality Plan", ru: "График продаж · Сезонность" },
  scheduleHint: { zh: "按产品填写每月计划销量。默认项目按冷启动 + 10-12月冬季旺季曲线分配，不是平均月销；清空后就是 0，不会自动均分。", en: "Enter monthly planned sales per SKU. Defaults use cold-start plus Oct-Dec seasonality, not an average month.", ru: "Введите план продаж по месяцам. По умолчанию учтена сезонность." },
  forecastMonths: { zh: "预测月数", en: "Forecast Months", ru: "Месяцев прогноза" },
  months: { zh: "个月", en: "months", ru: "мес." },
  filterSku: { zh: "一键匹配商品（输入型号）", en: "Filter SKUs", ru: "Фильтр SKU" },
  seasonalCurve: { zh: "冬季旺季曲线", en: "Winter Seasonality", ru: "Зимняя сезонность" },
  linearDist: { zh: "平均分配（仅校验）", en: "Even Check", ru: "Равномерно" },
  frontload: { zh: "前重后轻", en: "Frontload", ru: "С начала" },
  bellCurve: { zh: "钟形曲线", en: "Bell Curve", ru: "Гаусс" },
  resetDist: { zh: "清空", en: "Clear", ru: "Очистить" },
  sku: { zh: "产品型号", en: "SKU", ru: "SKU" },
  total: { zh: "总量", en: "Total", ru: "Всего" },
  totalPieces: { zh: "总量（件）", en: "Total (pcs)", ru: "Всего (шт.)" },
  totalAmountRub: { zh: "总额（₽）", en: "Total (₽)", ru: "Всего (₽)" },
  allocated: { zh: "已分配", en: "Allocated", ru: "Распред." },
  allocatedPieces: { zh: "已分配（件）", en: "Allocated (pcs)", ru: "Распред. (шт.)" },
  unitPieces: { zh: "件", en: "pcs", ru: "шт." },
  unitRub: { zh: "₽", en: "₽", ru: "₽" },
  monthLabel: { zh: "M", en: "M", ru: "М" },

  // === Projection Tab ===
  projTitle: { zh: "现金流预测", en: "Cash Flow Forecast", ru: "Прогноз денежного потока" },
  currentMonth: { zh: "当前月份", en: "Current Month", ru: "Текущий месяц" },
  monthN: { zh: "第 {n} 月", en: "Month {n}", ru: "Месяц {n}" },
  maxInvestment: { zh: "最大资金占用", en: "Max Capital Required", ru: "Макс. вложения" },
  cashBalance: { zh: "最后账上还剩现金", en: "Final Cash After Partner Payout", ru: "Итоговый кэш после выплаты партнеру" },
  totalProfit: { zh: "累计利润", en: "Total Profit", ru: "Общая прибыль" },
  vatThreshold: { zh: "增值税（VAT）触发阈值监控", en: "VAT Threshold Monitor", ru: "Мониторинг порога НДС" },
  vatAutoLabel: { zh: "营收过20M ₽自动触发增值税（VAT）", en: "Auto-trigger VAT above 20M ₽", ru: "Авто НДС при выручке >20М ₽" },
  cumCashChart: { zh: "累积现金流（含投资支出）", en: "Cumulative Cash (incl. investment)", ru: "Накопленный кэш (с инвест.)" },
  monthlyNetProfit: { zh: "本月经营利润分布", en: "Monthly Net Profit", ru: "Помесячная прибыль" },
  projParams: { zh: "预测参数", en: "Projection Parameters", ru: "Параметры прогноза" },
  projMonths: { zh: "预测月数", en: "Forecast Months", ru: "Мес. прогноза" },
  partnerShare: { zh: "合伙人分润比例", en: "Partner Split Ratio", ru: "Доля партнёра" },
  withdrawalTitle: { zh: "分润排期 · 每月提取金额", en: "Withdrawal Schedule · Monthly Distribution", ru: "График распределения · Помесячно" },
  withdrawalHint: { zh: "每月填入要拿出来分的钱（₽），0 = 不拿。金额不能超过本月经营利润。", en: "Enter RUB amount to withdraw for distribution each month. 0 = no withdrawal. Capped at monthly net profit.", ru: "Введите сумму (₽) для распределения. 0 = без распределения. Не более месячной прибыли." },
  withdrawalLabel: { zh: "本月拿出来分的钱（₽）", en: "Withdrawal (₽)", ru: "Распределение (₽)" },
  withdrawalAmount: { zh: "金额（₽）", en: "Amount ₽", ru: "Сумма ₽" },
  resetWithdrawal: { zh: "重置分润", en: "Reset Withdrawal", ru: "Сброс распред." },
  withdrawalSplitNote: { zh: "拿出来的钱按 {pct}% 分给合伙人，其余留给自己。没拿出来的利润继续留在项目里。", en: "Withdrawn amount split {pct}% to partner. Remainder stays in project.", ru: "Распределяется {pct}% партнёру. Остаток — в проекте." },
  fixedCost: { zh: "每月固定支出（薪资/工具）", en: "Monthly Fixed Cost", ru: "Пост. расходы/мес." },
  priorRevenue: { zh: "本年已累计营收（跨阈值用）", en: "Prior Year Revenue", ru: "Выручка за пред. период" },
  projNote: { zh: "月度测算按销售排期、售价排期和平台综合扣费排期联动计算；默认采用冷启动 + 冬季旺季曲线，不按全年平均摊销。", en: "Projection follows sales, price and platform-burden schedules; defaults use seasonality rather than an even average.", ru: "Прогноз основан на графиках продаж, цены и расходов." },
  cashFlowDetail: { zh: "月度损益与现金流明细", en: "Monthly P&L & Cash Flow Detail", ru: "Помесячный P&L и кэш" },
  cashFlowWarning: { zh: "利润视角 vs 现金流视角", en: "Two different views: P&L vs Cash Flow", ru: "Два ракурса: P&L и Кэш" },

  // === Table Headers (Projection) ===
  thMonth: { zh: "月份", en: "Month", ru: "Месяц" },
  thSoldQty: { zh: "售出", en: "Sold", ru: "Продано" },
  thRevenue: { zh: "销售回款", en: "Revenue", ru: "Выручка" },
  thCogs: { zh: "销货成本", en: "COGS", ru: "Себест." },
  thExpenses: { zh: "仓储及费用", en: "Expenses", ru: "Расходы" },
  thGrossProfit: { zh: "毛利/税前", en: "Gross Profit", ru: "Валовая" },
  thTax: { zh: "税额", en: "Tax", ru: "Налог" },
  thNetProfit: { zh: "本月经营利润", en: "Net Profit", ru: "Чист. приб." },
  thPartner: { zh: "分给合伙人的钱（金额）", en: "Partner", ru: "Партнёр" },
  thDistributed: { zh: "本月拿出来分的钱（金额）", en: "Distributed", ru: "Распред." },
  thOwner: { zh: "留给自己的钱（金额）", en: "Owner", ru: "Владелец" },
  thCashFlow: { zh: "本月实际现金进出（金额）", en: "Cash Flow", ru: "Кэш" },
  thCumCash: { zh: "账上累计现金（金额）", en: "Cum. Cash", ru: "Накоп. кэш" },
  thDamageLoss: { zh: "货损", en: "Damage", ru: "Потери" },
  initialRow: { zh: "初始（备货）", en: "Initial (Stock)", ru: "Начальные" },

  // === Settings Tab ===
  taxRegime: { zh: "俄罗斯税制选择", en: "Russian Tax Regime", ru: "Налоговый режим РФ" },
  taxRegimeKicker: { zh: "Tax Regime · 2026", en: "Tax Regime · 2026", ru: "Налоговый режим · 2026" },
  globalParams: { zh: "全局参数", en: "Global Parameters", ru: "Глобальные параметры" },
  globalParamsKicker: { zh: "Global Parameters", en: "Global Parameters", ru: "Параметры" },
  exchangeRate: { zh: "汇率（1元 → ? 卢布）", en: "Exchange Rate (1 CNY → ? RUB)", ru: "Курс (1 CNY → ? RUB)" },
  damageRate: { zh: "损耗率", en: "Damage Rate", ru: "Потери" },
  shippingPerUnit: { zh: "到俄运费（待报价）", en: "RU Shipping (Pending Quote)", ru: "Доставка РФ (по запросу)" },
  shippingMode: { zh: "清关方式", en: "Customs Mode", ru: "Режим таможни" },
  shippingManual: { zh: "手动输入", en: "Manual", ru: "Вручную" },
  shippingGray: { zh: "灰关（按重量）", en: "Gray (by weight)", ru: "Серая (вес)" },
  shippingWhite: { zh: "白关（按体积）", en: "White (by volume)", ru: "Белая (объём)" },
  grayShipPrice: { zh: "灰关运费单价", en: "Gray Customs Rate", ru: "Тариф серой" },
  whiteShipPrice: { zh: "白关运费单价", en: "White Customs Rate", ru: "Тариф белой" },
  weightKg: { zh: "单件重量", en: "Unit Weight", ru: "Вес ед." },
  volumeLWH: { zh: "单件体积 (长×宽×高)", en: "Unit Volume (L×W×H)", ru: "Объём (Д×Ш×В)" },
  volL: { zh: "长", en: "L", ru: "Д" },
  volW: { zh: "宽", en: "W", ru: "Ш" },
  volH: { zh: "高", en: "H", ru: "В" },
  calcShippingCost: { zh: "运费", en: "Shipping", ru: "Доставка" },
  grayNoVatNote: { zh: "⚠ 灰关没有进口时付的增值税（进项VAT）发票，在俄罗斯一般税制（OSN）下不可抵扣", en: "⚠ Gray customs: no import VAT invoice, non-deductible under OSN", ru: "⚠ Серая: нет вх. НДС, не вычитается при ОСН" },
  labelingCost: { zh: "贴标/本地化（暂不计）", en: "Labeling / Localization (excluded)", ru: "Маркировка (не учт.)" },
  oneTimeCosts: { zh: "首批启动费（不含库存/广告/物流）", en: "One-time Setup Costs", ru: "Разовые расходы" },
  incomeBasis: { zh: "收入确认基础", en: "Income Recognition", ru: "Признание дохода" },
  incomeBasisKicker: { zh: "Income Recognition", en: "Income Recognition", ru: "Признание дохода" },
  basisPayout: { zh: "平台到手金额（M × 售价 − 平台综合扣费）", en: "Platform Payout (M × Price − Fees)", ru: "Выплата площадки" },
  basisPayoutDesc: { zh: "实操推荐：以平台实际回款为税基入账。", en: "Recommended: use actual platform payout as tax base.", ru: "Рекомендуется: выплата площадки как налоговая база." },
  basisList: { zh: "全额上架价（M × 售价）", en: "Full List Price (M × Price)", ru: "Полная цена (М × Цена)" },
  basisListDesc: { zh: "最保守：按全额卖家标价确认收入，税负会更高。", en: "Conservative: includes platform fees in tax base.", ru: "Консервативно: платформенные сборы в налоговую базу." },

  // === Footer ===
  footerText: { zh: "数据基于 联邦法 №425-FZ（2025.11.28，2026.1.1生效）。俄罗斯简化税制（USN）门槛 2026=20M / 2027=15M / 2028=10M ₽。", en: "Based on Federal Law №425-FZ (2025.11.28, effective 2026.1.1). USN thresholds: 2026=20M / 2027=15M / 2028=10M ₽.", ru: "По ФЗ №425-ФЗ (28.11.2025, с 01.01.2026). Пороги УСН: 2026=20М / 2027=15М / 2028=10М ₽." },
  footerDisclaimer: { zh: "本工具仅供测算参考，最终申报请咨询当地会计师。", en: "For estimation only. Consult a local accountant for filings.", ru: "Только для оценки. Обратитесь к бухгалтеру." },

  // === Exchange Rate ===
  liveRate: { zh: "实时汇率", en: "Live Rate", ru: "Курс онлайн" },
  rateUpdated: { zh: "汇率已更新", en: "Rate updated", ru: "Курс обновлён" },
  rateFailed: { zh: "汇率获取失败，使用手动值", en: "Rate fetch failed, using manual", ru: "Ошибка курса, ручной ввод" },
  rateManual: { zh: "手动", en: "Manual", ru: "Вручную" },
  rateLive: { zh: "实时", en: "Live", ru: "Онлайн" },

  // === Misc ===
  confirmClear: { zh: "确定清空所有商品？此操作不可撤销。", en: "Clear all products? This cannot be undone.", ru: "Очистить все товары? Это необратимо." },
  confirmReset: { zh: "重置为样例数据？当前编辑会丢失。", en: "Reset to sample data? Current edits will be lost.", ru: "Сбросить до примера? Текущие данные будут потеряны." },
  dualTrackNote: { zh: "供应商报价/预估采购价和报关申报价均按上架销售单位填写：6只装、12件套、壶杯套装都按整套计，不按单只杯子计。在俄罗斯简化税制（USN）15% 或俄罗斯一般税制（OSN）下，税务局只认可有白关票据的“报关申报”成本；正式报价后需替换并复核税务损耗。", en: "Actual and declared costs are per sellable listing unit, not per individual piece. Under USN 15% or OSN, only declared customs costs are deductible.", ru: "Фактическая и декларируемая цена указаны за продаваемую единицу/набор, не за штуку. При УСН 15% или ОСН признаются только задекларированные расходы." },

  // === Charts ===
  chartBreakEven: { zh: "回本", en: "Break-even", ru: "Окупаемость" },
  chartCumCash: { zh: "累积现金", en: "Cum. Cash", ru: "Накоп. кэш" },
  chartMonthlyNet: { zh: "月度利润", en: "Monthly Net", ru: "Мес. прибыль" },

  // === Project Management ===
  projectUntitled: { zh: "未命名项目", en: "Untitled Project", ru: "Без названия" },
  projectCurrentLabel: { zh: "当前项目", en: "Current Project", ru: "Текущий проект" },
  projectSave: { zh: "保存到本机", en: "Save locally", ru: "Сохранить локально" },
  projectSaveAs: { zh: "另存为…", en: "Save As…", ru: "Сохранить как…" },
  projectSaveAsPrompt: { zh: "请输入新项目名称：", en: "Enter new project name:", ru: "Введите название проекта:" },
  projectNew: { zh: "新建项目", en: "New Project", ru: "Новый проект" },
  projectNewConfirm: { zh: "新建项目会清空当前数据，确定？", en: "Create new project? Current data will be cleared.", ru: "Создать новый проект? Текущие данные будут очищены." },
  projectNewNamePrompt: { zh: "请输入项目名称：", en: "Enter project name:", ru: "Введите название проекта:" },
  projectList: { zh: "项目列表", en: "Projects", ru: "Проекты" },
  publicProjects: { zh: "线上公开项目", en: "Published projects", ru: "Опубликованные проекты" },
  publicProjectsHint: { zh: "这些项目已经随网站发布，别人打开同一个网站也能看到。", en: "These projects are published with the site and visible to others.", ru: "Эти проекты опубликованы на сайте и видны другим." },
  localProjects: { zh: "本机保存项目", en: "Local projects", ru: "Локальные проекты" },
  localProjectsHint: { zh: "这里的数据只保存在当前浏览器，别人打开链接看不到；要给别人看，请用上方线上项目、分享链接，或导出 JSON 后发给对方。", en: "These are saved only in this browser. Others cannot see them unless you use a published project, share link, or exported JSON.", ru: "Они сохранены только в этом браузере. Другие их не видят без опубликованного проекта, ссылки или JSON." },
  projectOpen: { zh: "打开", en: "Open", ru: "Открыть" },
  projectOpenConfirm: { zh: "打开项目 \"{name}\"？当前未保存的修改会丢失。", en: "Open \"{name}\"? Unsaved changes will be lost.", ru: "Открыть \"{name}\"? Несохранённые данные будут потеряны." },
  projectRename: { zh: "重命名", en: "Rename", ru: "Переименовать" },
  projectRenamePrompt: { zh: "输入新名称：", en: "Enter new name:", ru: "Новое название:" },
  projectDelete: { zh: "删除", en: "Delete", ru: "Удалить" },
  projectDeleteConfirm: { zh: "确定删除项目 \"{name}\"？此操作不可撤销。", en: "Delete project \"{name}\"? This cannot be undone.", ru: "Удалить проект \"{name}\"? Это необратимо." },
  projectExportJson: { zh: "导出 JSON", en: "Export JSON", ru: "Экспорт JSON" },
  projectImportJson: { zh: "导入 JSON", en: "Import JSON", ru: "Импорт JSON" },
  projectImportSuccess: { zh: "✓ 已导入项目 \"{name}\"", en: "✓ Imported project \"{name}\"", ru: "✓ Импортирован \"{name}\"" },
  projectImportFail: { zh: "导入失败：文件格式不正确", en: "Import failed: invalid file format", ru: "Ошибка импорта: неверный формат" },
  projectSaved: { zh: "✓ 已保存到本机 \"{name}\"", en: "✓ Saved locally \"{name}\"", ru: "✓ Сохранено локально \"{name}\"" },
  projectLoaded: { zh: "✓ 已加载 \"{name}\"", en: "✓ Loaded \"{name}\"", ru: "✓ Загружено \"{name}\"" },
  projectLastSaved: { zh: "保存于 {time}", en: "Saved {time}", ru: "Сохранено {time}" },
  projectSkuCount: { zh: "{n} 个产品", en: "{n} SKUs", ru: "{n} SKU" },
  projectCurrent: { zh: "（当前）", en: "(current)", ru: "(текущий)" },
  projectNameExists: { zh: "该名称已存在，是否覆盖？", en: "Name already exists. Overwrite?", ru: "Название уже существует. Перезаписать?" },
  projectDuplicate: { zh: "复制", en: "Duplicate", ru: "Копия" },

  // === Tax Breakdown Details ===
  taxVatPartLabel: { zh: "增值税（VAT）", en: "VAT", ru: "НДС" },
  taxUsnPartLabel: { zh: "俄罗斯简化税制（USN）", en: "USN / STS", ru: "УСН" },
  inputVATLabel: { zh: "· 进口时付的增值税（进项VAT，按报关申报价计提）", en: "· Input VAT (on declared value)", ru: "· Вх. НДС (по декларации)" },
  outputVATLabel: { zh: "· 卖出时产生的增值税（销项VAT，向消费者收取）", en: "· Output VAT (charged to buyer)", ru: "· Исх. НДС (с покупателя)" },
  currentScheme: { zh: "当前方案：", en: "Current scheme: ", ru: "Текущая схема: " },

  // === Product Ranking / Table ===
  noProducts: { zh: "暂无商品。", en: "No products yet.", ru: "Товаров пока нет." },
  totalRow: { zh: "合计", en: "Total", ru: "Итого" },
  confirmDeleteProd: { zh: "删除 {id}？", en: "Delete {id}?", ru: "Удалить {id}?" },

  // === Product Editor ===
  editorFields: { zh: "编辑字段", en: "Edit Fields", ru: "Редактирование" },
  editorCalcDetail: { zh: "计算明细 / 单位", en: "Calc Details / Unit", ru: "Расчёт / Единица" },
  fieldProductId: { zh: "产品 ID", en: "Product ID", ru: "ID товара" },
  fieldActualCost: { zh: "供应商报价/预估采购价（¥/销售单位）", en: "Estimated Cost / sellable unit (CNY)", ru: "Факт. цена / ед. продажи (CNY)" },
  fieldDeclaredCost: { zh: "报关申报价（¥/销售单位）", en: "Estimated Declared Cost / unit (CNY)", ru: "Деклар. цена / ед. (CNY)" },
  fieldQty: { zh: "数量 (销售单位)", en: "Qty (sellable units)", ru: "Кол-во (ед. продажи)" },
  fieldWeight: { zh: "重量 (kg)", en: "Weight (kg)", ru: "Вес (кг)" },
  fieldListPrice: { zh: "上架售价 (₽)", en: "List Price (₽)", ru: "Цена (₽)" },
  fieldPlatformFee: { zh: "平台综合扣费（₽/销售单位）", en: "Platform Burden (₽/unit)", ru: "Расходы площадки (₽/ед.)" },
  fieldWarehouse: { zh: "海外仓费用 (₽/销售单位)", en: "Overseas Warehouse (₽/unit)", ru: "Склад (₽/ед.)" },
  fieldMgmt: { zh: "管理费 (₽/销售单位)", en: "Mgmt Fee (₽/unit)", ru: "Управление (₽/ед.)" },
  vatBasisTag: { zh: "增值税基础", en: "VAT Base", ru: "База НДС" },
  calcActualRub: { zh: "采购卢布/销售单位", en: "Actual RUB / sellable unit", ru: "Факт. ₽ / ед." },
  calcDeclaredRub: { zh: "报关申报卢布/销售单位", en: "Declared RUB / sellable unit", ru: "Деклар. ₽ / ед." },
  calcShipping: { zh: "+ 到俄运费（未填则不计）", en: "+ RU Shipping (0 = excluded)", ru: "+ Доставка РФ (0 = не учтено)" },
  calcLabeling: { zh: "+ 贴标/本地化（暂不计）", en: "+ Labeling / Localization (excluded)", ru: "+ Маркировка (не учт.)" },
  calcUnitCost: { zh: "= 销售单位成本", en: "= Sellable Unit Cost", ru: "= Себест. ед. продажи" },
  calcUnitPayout: { zh: "扣平台后回款", en: "Payout After Platform", ru: "Выплата после площадки" },
  calcUnitGross: { zh: "销售单位毛利", en: "Sellable Unit Gross", ru: "Валовая/ед. продажи" },
  calcUnitNet: { zh: "销售单位利润", en: "Sellable Unit Net Profit", ru: "Чистая/ед. продажи" },
  calcInputVAT: { zh: "· 进口时付的增值税（进项VAT）/件", en: "· Input VAT/pc", ru: "· Вх. НДС/шт" },
  calcOutputVAT: { zh: "· 卖出时产生的增值税（销项VAT）/件", en: "· Output VAT/pc", ru: "· Исх. НДС/шт" },
  tagMargin: { zh: "利润率", en: "Margin", ru: "Маржа" },
  tagEffQty: { zh: "有效销售单位", en: "Eff. Units", ru: "Эфф. ед." },

  // === VAT Threshold Monitor ===
  vatAutoTrigger: { zh: "营收过20M ₽自动触发增值税（VAT）", en: "Auto-trigger VAT above 20M ₽", ru: "Авто НДС при выручке >20М ₽" },
  vatAutoDesc: { zh: "开启后，模型会跟踪你年度累计营收：", en: "When enabled, tracks annual cumulative revenue:", ru: "При включении отслеживается годовая выручка:" },
  vatTier0Desc: { zh: " 免增值税（VAT）", en: " No VAT", ru: " Без НДС" },
  vatTier1Desc: { zh: " 自动加增值税（VAT）5%", en: " auto VAT 5%", ru: " авто НДС 5%" },
  vatTier2Desc: { zh: " 增值税（VAT）7%", en: " VAT 7%", ru: " НДС 7%" },
  vatTier3Desc: { zh: " 强制俄罗斯一般税制（OSN：增值税（VAT）22% + 利润税）。", en: " mandatory OSN (VAT 22% + Profit Tax).", ru: " обязательно ОСН (НДС 22% + налог)." },
  vatFixedNote: { zh: "当前已固定为", en: "Currently fixed at", ru: "Зафиксировано:" },
  vatSwitchHint: { zh: "想看动态触发效果，请先在“参数与税制”切回俄罗斯简化税制（USN）6% 或 15%。", en: "To see dynamic triggers, switch to USN 6% or 15% in Settings.", ru: "Для динамического НДС переключитесь на УСН 6% или 15%." },
  vatCumRevenue: { zh: "本年累计营收（含起始值）", en: "Annual Cumulative Revenue", ru: "Годовая выручка (накоп.)" },
  vatTagNoVat: { zh: "免增值税（VAT）0–20M", en: "No VAT 0–20M", ru: "Без НДС 0–20М" },
  vatTag5: { zh: "增值税（VAT）5% 20M–250M", en: "VAT 5% 20M–250M", ru: "НДС 5% 20М–250М" },
  vatTag7: { zh: "增值税（VAT）7% 250M–450M", en: "VAT 7% 250M–450M", ru: "НДС 7% 250М–450М" },
  vatTagOsn: { zh: "俄罗斯一般税制（OSN）增值税22% >450M", en: "OSN 22% >450M", ru: "ОСН 22% >450М" },
  vatTriggeredTitle: { zh: "第 {n} 个月起触发增值税（VAT）", en: "VAT triggered from month {n}", ru: "НДС с {n}-го месяца" },
  vatTriggeredDesc1: { zh: "累计营收在 M{n} 突破 20M ₽，从该月起自动加增值税（VAT）5%。", en: "Cumulative revenue exceeded 20M ₽ in M{n}, auto VAT 5% applied.", ru: "Выручка превысила 20М ₽ в M{n}, авто НДС 5%." },
  vatTriggeredDesc2: { zh: "如果到下一年度，本年累计会重置；但若全年都超过门槛，下一整年都需要继续缴增值税（VAT）。", en: "Annual reset applies, but if threshold exceeded all year, VAT continues next year.", ru: "Годовой сброс, но при превышении весь год НДС продолжается." },
  vatTriggeredTotal: { zh: "总计增值税（VAT）缴纳：", en: "Total VAT paid: ", ru: "Итого НДС: " },
  vatNotTriggered: { zh: "预测期内未触发增值税（VAT）", en: "VAT not triggered in forecast", ru: "НДС не активирован в прогнозе" },
  vatDistanceHint: { zh: "离 20M 阈值还有 {amount}。如果要扩大销售规模，可以延长预测期或提高月销量看看在第几个月会被触发。", en: "{amount} remaining to 20M threshold. Extend forecast or increase sales to see when VAT triggers.", ru: "До порога 20М осталось {amount}. Увеличьте прогноз или объём продаж." },

  // === Projection Detail Table ===
  projTaxNote: { zh: "月度税：每月按当月利润现算（实际俄罗斯简化税制（USN）为季度申报，俄罗斯一般税制（OSN）为月度申报增值税（VAT）；这里按月分摊以便观察）。", en: "Monthly tax calculated per month (actual STS is quarterly, GTS monthly VAT; shown monthly for analysis).", ru: "Помесячный налог (фактически УСН поквартально, ОСН помесячно НДС; показано помесячно)." },
  projInputVATNote: { zh: "进口时付的增值税（进项VAT）余额随卖出时产生的增值税（销项VAT）滚动抵扣；", en: "Input VAT credit rolls over monthly; ", ru: "Вх. НДС зачитывается помесячно; " },
  projInputVATLeft: { zh: "期末仍有 {amount} 未用完", en: "{amount} remaining unused", ru: "осталось {amount}" },
  projInputVATUsed: { zh: "已用完", en: "fully used", ru: "полностью использовано" },
  projCashVsPnl: { zh: "\"本月经营利润\" 和 \"本月实际现金进出\" 是两个视角：", en: "\"Net Profit\" vs \"Cash Flow\" — two views:", ru: "\"Чист. прибыль\" vs \"Кэш\" — два ракурса:" },
  projNetLabel: { zh: "本月经营利润", en: "Net Profit", ru: "Чист. прибыль" },
  projNetDesc: { zh: "= 营收 − 销货成本 − 海外仓费 − 管理费 − 税。它看的是这个月经营赚了多少。", en: "= Revenue − COGS − Overseas WH − Mgmt − Tax (accounting profit)", ru: "= Выручка − Себест. − Склад − Упр. − Налог" },
  projCashLabel: { zh: "本月实际现金进出", en: "Cash Flow", ru: "Кэш" },
  projCashDesc: { zh: "= 营收 − 海外仓费 − 管理费 − 税 − 分给合伙人的钱。M0 已经付过全部库存款，月度不再重复扣销货成本。", en: "= Revenue − Overseas WH − Mgmt − Tax − Partner (M0 paid all inventory, no monthly COGS)", ru: "= Выручка − Склад − Упр. − Налог − Партнёр" },
  thTaxTier: { zh: "本月适用税制", en: "Tax Tier", ru: "Режим" },
  thSoldQtyD: { zh: "销售件数（件）", en: "Units Sold (pcs)", ru: "Продано (шт.)" },
  thRevenueD: { zh: "营收金额", en: "Revenue", ru: "Выручка" },
  thCogsD: { zh: "销货成本金额", en: "COGS", ru: "Себест." },
  thWhMgmt: { zh: "海外仓+管理金额", en: "WH+Mgmt", ru: "Склад+Упр." },
  thFixedCost: { zh: "固定支出金额", en: "Fixed Cost", ru: "Пост. расх." },
  thMonthlyNet: { zh: "本月经营利润金额", en: "Net Profit", ru: "Чист. приб." },
  thCashFlowD: { zh: "本月实际现金进出金额", en: "Cash Flow", ru: "Кэш" },
  thCumCashD: { zh: "账上累计现金金额", en: "Cum. Cash", ru: "Накоп. кэш" },
  investLabel: { zh: "(投资)", en: "(invest)", ru: "(инвест.)" },
  vatFixedSuffix: { zh: "(固定)", en: "(fixed)", ru: "(фикс.)" },
  // === VAT Tier Labels (cash flow table tax-regime column) ===
  vatLabelNoVat: { zh: "免增值税（VAT）", en: "No VAT", ru: "Без НДС" },
  vatLabelVat5: { zh: "增值税（VAT）5%", en: "VAT 5%", ru: "НДС 5%" },
  vatLabelVat7: { zh: "增值税（VAT）7%", en: "VAT 7%", ru: "НДС 7%" },
  vatLabelOsn22: { zh: "俄罗斯一般税制（OSN）增值税（VAT）22%", en: "VAT 22% (GTS)", ru: "НДС 22% (ОСН)" },
  vatLabelFixed5: { zh: "增值税（VAT）5%（固定）", en: "VAT 5% (fixed)", ru: "НДС 5% (фикс.)" },
  vatLabelFixed7: { zh: "增值税（VAT）7%（固定）", en: "VAT 7% (fixed)", ru: "НДС 7% (фикс.)" },
  vatLabelFixedOsn: { zh: "增值税（VAT）{rate}%（固定）", en: "VAT {rate}% (fixed)", ru: "НДС {rate}% (фикс.)" },

  // === Tax Scheme Picker ===
  taxUsn6Label: { zh: "俄罗斯简化税制（USN）6%：按收入", en: "STS 6% (on revenue)", ru: "УСН 6% (по доходам)" },
  taxUsn6Desc: { zh: "按全部收入征6%。营收 ≤ 20M₽ (2026) 免增值税（VAT）。", en: "6% on all revenue. ≤ 20M₽ (2026) VAT-exempt.", ru: "6% от дохода. ≤ 20М₽ (2026) без НДС." },
  taxUsn15Label: { zh: "俄罗斯简化税制（USN）15%：收入−支出", en: "STS 15% (revenue−expenses)", ru: "УСН 15% (доходы−расходы)" },
  taxUsn15Desc: { zh: "(收入−支出) × 15%，最低 1% × 收入。营收 ≤ 20M₽ 免增值税（VAT）。", en: "(Revenue−Expenses) × 15%, min 1% × revenue. ≤ 20M₽ VAT-exempt.", ru: "(Доход−Расход) × 15%, мин. 1% × доход. ≤ 20М₽ без НДС." },
  taxUsn6v5Label: { zh: "俄罗斯简化税制（USN）6% + 增值税（VAT）5%（无进项抵扣）", en: "STS 6% + VAT 5% (no input credit)", ru: "УСН 6% + НДС 5% (без вх. вычета)" },
  taxUsn6v5Desc: { zh: "营收 20–250M₽ 适用。收入 × 6% + 增值税（VAT）5%，不可抵扣进口时付的增值税（进项VAT）。", en: "Revenue 20–250M₽. Revenue × 6% + VAT 5%, no input credit.", ru: "Выручка 20–250М₽. Доход × 6% + НДС 5% без вычета." },
  taxUsn6v7Label: { zh: "俄罗斯简化税制（USN）6% + 增值税（VAT）7%（无进项抵扣）", en: "STS 6% + VAT 7% (no input credit)", ru: "УСН 6% + НДС 7% (без вх. вычета)" },
  taxUsn6v7Desc: { zh: "营收 250–450M₽ 适用。收入 × 6% + 增值税（VAT）7%，不可抵扣进口时付的增值税（进项VAT）。", en: "Revenue 250–450M₽. Revenue × 6% + VAT 7%, no input credit.", ru: "Выручка 250–450М₽. Доход × 6% + НДС 7% без вычета." },
  taxUsn15v5Label: { zh: "俄罗斯简化税制（USN）15% + 增值税（VAT）5%（无进项抵扣）", en: "STS 15% + VAT 5% (no input credit)", ru: "УСН 15% + НДС 5% (без вх. вычета)" },
  taxUsn15v5Desc: { zh: "营收 20–250M₽ 适用。增值税（VAT）5% 不可抵扣进口时付的增值税（进项VAT）。", en: "Revenue 20–250M₽. VAT 5% without input credit.", ru: "Выручка 20–250М₽. НДС 5% без вх. вычета." },
  taxUsn15v7Label: { zh: "俄罗斯简化税制（USN）15% + 增值税（VAT）7%（无进项抵扣）", en: "STS 15% + VAT 7% (no input credit)", ru: "УСН 15% + НДС 7% (без вх. вычета)" },
  taxUsn15v7Desc: { zh: "营收 250–450M₽ 适用。增值税（VAT）7% 不可抵扣进口时付的增值税（进项VAT）。", en: "Revenue 250–450M₽. VAT 7% without input credit.", ru: "Выручка 250–450М₽. НДС 7% без вх. вычета." },
  taxOsnLabel: { zh: "俄罗斯一般税制（OSN）：增值税（VAT）22% + 利润税 25%", en: "GTS (VAT 22% + Profit Tax 25%)", ru: "ОСН (НДС 22% + налог на прибыль 25%)" },
  taxOsnDesc: { zh: "2026年增值税（VAT）20→22%，可用报关申报价对应的进口时付的增值税（进项VAT）抵扣。利润税 25%。", en: "2026 VAT 20→22%, input VAT deductible. Profit tax 25%.", ru: "2026 НДС 20→22%, вх. НДС вычитается. Налог на прибыль 25%." },
  taxCustomLabel: { zh: "自定义税率", en: "Custom Tax Rate", ru: "Своя ставка" },
  taxCustomDesc: { zh: "按税前利润 × 自定义税率。", en: "Pre-tax profit × custom rate.", ru: "Прибыль до налогов × своя ставка." },
  customTaxRateLabel: { zh: "自定义税率（按税前利润）", en: "Custom Rate (on pre-tax profit)", ru: "Своя ставка (от прибыли)" },
  vatRateLabel: { zh: "增值税（VAT）率 (2026: 22%)", en: "VAT Rate (2026: 22%)", ru: "Ставка НДС (2026: 22%)" },
  profitTaxLabel: { zh: "利润税率 (默认 25%)", en: "Profit Tax Rate (default 25%)", ru: "Налог на прибыль (25%)" },
  osnNote: { zh: "俄罗斯一般税制（OSN）下，每个产品可单独填“报关申报价（元）”。进口时付的增值税（进项VAT）= 报关申报价 × 汇率 × 数量 × 22%（导入时支付），可滚动抵扣卖出时产生的增值税（销项VAT）。", en: "Under GTS, each SKU can have a \"Declared Cost\". Input VAT = Declared × Rate × Qty × 22% (paid at import), rolled over monthly.", ru: "При ОСН для каждого SKU можно указать \"деклар. цену\". Вх. НДС = Деклар. × Курс × Кол-во × 22%, зачитывается помесячно." },

  // === Params Panel ===
  paramExchangeRate: { zh: "汇率（1元 ≈ ? 卢布）", en: "Exchange Rate (1 CNY ≈ ? RUB)", ru: "Курс (1 CNY ≈ ? RUB)" },
  paramUsdRate: { zh: "美元汇率（1$ ≈ ? 卢布）", en: "USD Rate (1 USD ≈ ? RUB)", ru: "Курс USD (1 $ ≈ ? RUB)" },
  paramDamageRate: { zh: "货损率", en: "Damage Rate", ru: "Процент потерь" },
  paramShipping: { zh: "到俄罗斯单件运费", en: "Shipping per Unit to Russia", ru: "Доставка за ед. в Россию" },
  paramLabeling: { zh: "贴标/本地化（暂不计）", en: "Labeling / Localization (excluded)", ru: "Маркировка (не учт.)" },
  paramOneTime: { zh: "首批启动费（样品/包装/拍摄/合规）", en: "One-time Costs (design/photo/compliance)", ru: "Разовые расходы (дизайн/фото/серт.)" },

  // === Price Schedule ===
  priceScheduleTitle: { zh: "售价排期 · 按月调价", en: "Price Schedule · Monthly Pricing", ru: "График цен · Помесячно" },
  priceScheduleHint: { zh: "默认继承商品统一售价，修改后变色显示。空白/0 = 使用默认值。", en: "Defaults to product base price. Modified values shown in color. Empty/0 = default.", ru: "По умолчанию базовая цена. Изменённые выделены цветом. Пусто/0 = по умолчанию." },
  feeScheduleTitle: { zh: "平台综合扣费排期 · 按月调整", en: "Platform Burden Schedule · Monthly Fees", ru: "График расходов площадки · Помесячно" },
  feeScheduleHint: { zh: "默认继承商品统一平台综合扣费。这里不是单一佣金，而是佣金、支付、平台物流/退货、广告促销预留等合计。", en: "Defaults to product base platform burden, including commission, payment, fulfillment/returns and promotion reserve.", ru: "По умолчанию базовые расходы площадки." },
  defaultPrice: { zh: "默认值", en: "Default", ru: "По умолч." },
  resetPrices: { zh: "重置售价", en: "Reset Prices", ru: "Сброс цен" },
  resetFees: { zh: "重置平台综合扣费", en: "Reset Fees", ru: "Сброс расходов" },
  priceLabel: { zh: "售价₽", en: "Price₽", ru: "Цена₽" },
  feeLabel: { zh: "综合扣费₽", en: "Fee₽", ru: "Расход₽" },

  // === Restock Schedule ===
  restockTitle: { zh: "补货排期 · 分批采购", en: "Restock Schedule · Batch Purchasing", ru: "График закупок · Партиями" },
  restockHint: { zh: "M0为首批采购，后续月份填入补货数量。0 = 不补货。", en: "M0 = initial batch. Fill restock qty for later months. 0 = no restock.", ru: "M0 = первая партия. Заполните кол-во для закупок. 0 = без закупки." },
  initialBatch: { zh: "首批 M0（件）", en: "Initial M0 (pcs)", ru: "Первая M0 (шт.)" },
  totalPurchased: { zh: "总采购（件）", en: "Total Purchased (pcs)", ru: "Всего закуплено (шт.)" },
  resetRestock: { zh: "重置补货", en: "Reset Restock", ru: "Сброс закупок" },
  colRestock: { zh: "补货（件/金额）", en: "Restock (pcs/amount)", ru: "Закупка (шт./сумма)" },
  colStock: { zh: "库存（件）", en: "Stock (pcs)", ru: "Остаток (шт.)" },
  stockWarning: { zh: "缺货", en: "Out of stock", ru: "Нехватка" },
  restockCostLabel: { zh: "补货支出", en: "Restock Cost", ru: "Расход на закупку" },
  cumPurchase: { zh: "累计采购", en: "Cum. Purchase", ru: "Накоп. закупка" },

  // === Help Panel ===
  helpTitle: { zh: "2026年俄罗斯税制要点", en: "2026 Russian Tax Reform", ru: "Налоговая реформа РФ 2026" },
  helpPractical: { zh: "跨境电商实务", en: "Cross-border E-commerce Tips", ru: "Практика кросс-бордер" },
  helpVatTitle: { zh: "增值税（VAT）标准税率：20% → 22%", en: "VAT Standard Rate: 20% → 22%", ru: "Ставка НДС: 20% → 22%" },
  helpVatDesc: { zh: "联邦法 №425-FZ（2025.11.28），2026.1.1起增值税（VAT）基础税率上调至22%。食品、儿童用品、药品保留10%。", en: "Federal Law №425-FZ (2025.11.28), VAT raised to 22% from 2026.1.1. Food, children's, medicine remain 10%.", ru: "ФЗ №425-ФЗ (28.11.2025), НДС до 22% с 01.01.2026. Продукты, детские, лекарства — 10%." },
  helpUsnTitle: { zh: "俄罗斯简化税制（USN）触发增值税（VAT）门槛大幅下调", en: "STS VAT Threshold Lowered", ru: "Пороги НДС при УСН снижены" },
  helpUsnDesc: { zh: "超过门槛后可选：5%（20–250M）/ 7%（250–450M）无进项抵扣，或标准 0%/10%/22% 可抵扣。", en: "Above threshold: 5% (20–250M) / 7% (250–450M) no input credit, or standard 0%/10%/22% with credit.", ru: "Выше порога: 5% (20–250М) / 7% (250–450М) без вычета, или 0%/10%/22% с вычетом." },
  helpUsnBaseTitle: { zh: "俄罗斯简化税制（USN）基本税率不变", en: "STS Base Rates Unchanged", ru: "Базовые ставки УСН без изменений" },
  helpUsnBaseDesc: { zh: "6%（按收入）和15%（按收入−支出）保持不变。俄罗斯简化税制（USN）15%最低税额为收入1%。", en: "6% (on revenue) and 15% (revenue−expenses) unchanged. Min tax 1% of revenue.", ru: "6% и 15% без изменений. Мин. налог 1% дохода." },
  helpProfitTitle: { zh: "利润税：25%（俄罗斯一般税制（OSN））", en: "Profit Tax: 25% (GTS)", ru: "Налог на прибыль: 25% (ОСН)" },
  helpProfitDesc: { zh: "2025起从20%上调。IT企业有5%优惠（至2030）。", en: "Raised from 20% since 2025. IT companies 5% (until 2030).", ru: "Повышен с 20% с 2025. IT — 5% (до 2030)." },
  helpVat22Title: { zh: "22% 是什么税？", en: "What is the 22% tax?", ru: "Что за налог 22%?" },
  helpVat22Desc: { zh: "2026年最常对应：① 新增值税（VAT）基础税率；② NDFL（个税）最高累进档（年收入>50M ₽）。计算器把22%按增值税（VAT）处理。", en: "In 2026: ① New VAT base rate; ② NDFL top bracket (>50M ₽/yr). Calculator treats 22% as VAT.", ru: "В 2026: ① Новая ставка НДС; ② НДФЛ макс. (>50М ₽/год). Калькулятор — 22% как НДС." },
  helpDeclaredTitle: { zh: "报关申报价 vs 供应商报价", en: "Declared vs Actual Cost", ru: "Деклар. vs Факт. цена" },
  helpDeclaredDesc: { zh: "报关申报价决定进口时付的增值税（进项VAT）和关税基础。这里的供应商报价/预估采购价、报关申报价都是按上架销售单位填写，不是按单只杯子：例如 TY1628 为6只装整套成本，TCF053/L12 为12件套整套成本。正式报价后需替换并重新核算。", en: "Customs declared value determines input VAT and duty base. Costs are per sellable listing unit, e.g. a 6-pack or 12-piece set, not per individual cup.", ru: "Деклар. цена определяет НДС и пошлины. Стоимость указана за продаваемый набор/единицу, не за отдельный стакан." },
  helpThresholdTitle: { zh: "⚠️ 营收逼近20M的策略", en: "⚠️ Near 20M Threshold Strategy", ru: "⚠️ Стратегия при 20М" },
  helpThresholdDesc: { zh: "① 拆分两个法人保持小规模；② 主动过线选5%/7%。5%无进项抵扣，但若你本来进口时付的增值税（进项VAT）就少，5%可能比俄罗斯简化税制（USN）15%更划算。", en: "① Split into two entities; ② Cross threshold, choose 5%/7%. If input VAT is small, 5% may beat standard 15%.", ru: "① Разделить на два юрлица; ② Перейти порог, выбрать 5%/7%. Если вх. НДС мал, 5% может быть выгоднее." },
  helpUsn6v15Title: { zh: "俄罗斯简化税制（USN）6% vs 15% 经验法则", en: "STS 6% vs 15% Rule of Thumb", ru: "УСН 6% vs 15% правило" },
  helpUsn6v15Desc: { zh: "可证明支出 > 收入60% → 选15%；否则选6%。跨境电商通常供应商报价、平台综合扣费和仓管占比高，多数情况15%更优。", en: "Provable expenses > 60% of revenue → choose 15%; otherwise 6%. Cross-border e-com usually has high costs, so 15% often wins.", ru: "Расходы > 60% дохода → 15%; иначе 6%. Кросс-бордер обычно с высокими расходами, 15% чаще выгоднее." },
  helpDamageTitle: { zh: "货损双计修正", en: "Damage Double-Count Fix", ru: "Исправление двойного учёта потерь" },
  helpDamageDesc: { zh: "原表\"货损\"被重复扣除。本计算器仅通过减少有效销量(97%)体现货损，不再额外重复扣减。", en: "Original sheet double-counted damage. This calculator only reduces effective qty (97%), no extra deduction.", ru: "В оригинале потери считались дважды. Калькулятор уменьшает эфф. кол-во (97%), без доп. вычета." },
};

// --- 创建翻译函数 ---
export const createT = (lang) => (key, params) => {
  const entry = DICT[key];
  if (!entry) return key;
  let text = entry[lang] || entry.zh || key;
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });
  }
  return text;
};

// --- 货币格式化工厂 ---
// exchangeRate = CNY→RUB,  usdRate = USD→RUB
export const createCurrencyFormatter = (lang, exchangeRate, usdRate = 95) => {

  const fmtRub = (v, digits = 0) => "₽ " + (Number(v) || 0).toLocaleString("ru-RU", { minimumFractionDigits: digits, maximumFractionDigits: digits });

  const fmtRubShort = (v) => {
    const n = Number(v) || 0;
    if (Math.abs(n) >= 1e6) return "₽" + (n / 1e6).toFixed(2) + "M";
    if (Math.abs(n) >= 1e3) return "₽" + (n / 1e3).toFixed(0) + "K";
    return "₽" + n.toFixed(0);
  };

  const fmtCny = (v) => "¥ " + (Number(v) || 0).toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const fmtCnyShort = (v) => {
    const n = Number(v) || 0;
    if (Math.abs(n) >= 1e6) return "¥" + (n / 1e6).toFixed(2) + "M";
    if (Math.abs(n) >= 1e4) return "¥" + (n / 1e4).toFixed(1) + "万";
    return "¥" + n.toFixed(0);
  };

  const fmtUsd = (v) => "$ " + (Number(v) || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const fmtUsdShort = (v) => {
    const n = Number(v) || 0;
    if (Math.abs(n) >= 1e6) return "$" + (n / 1e6).toFixed(2) + "M";
    if (Math.abs(n) >= 1e3) return "$" + (n / 1e3).toFixed(1) + "K";
    return "$" + n.toFixed(0);
  };

  const fmtPct = (v) => ((Number(v) || 0) * 100).toFixed(1) + "%";

  // 主显示金额（zh=¥, en=$, ru=₽）
  const fmtPrimary = (rubValue) => {
    if (lang === "zh") return fmtCnyShort(rubValue / exchangeRate);
    if (lang === "en") return fmtUsdShort(rubValue / usdRate);
    return fmtRubShort(rubValue);
  };

  // 主显示金额（完整精度，用于表格明细）
  const fmtPrimaryFull = (rubValue, digits = 0) => {
    if (lang === "zh") return fmtCny(rubValue / exchangeRate);
    if (lang === "en") return fmtUsd(rubValue / usdRate);
    return fmtRub(rubValue, digits);
  };

  // 辅显示金额（小字副信息：显示 ₽ 原始值）
  const fmtSecondary = (rubValue) => {
    return fmtRubShort(rubValue);
  };

  return { fmtRub, fmtRubShort, fmtCny, fmtCnyShort, fmtUsd, fmtUsdShort, fmtPct, fmtPrimary, fmtPrimaryFull, fmtSecondary };
};

// --- 实时汇率 Hook ---
export const useLiveRate = (manualRate, manualUsdRate = 95) => {
  const [liveRate, setLiveRate] = useState(null);       // CNY→RUB
  const [liveUsdRate, setLiveUsdRate] = useState(null);  // USD→RUB
  const [rateSource, setRateSource] = useState("manual"); // "manual" | "live"
  const [rateLoading, setRateLoading] = useState(false);

  const fetchRate = useCallback(async ({ activate = true } = {}) => {
    setRateLoading(true);
    try {
      const res = await fetch("https://open.er-api.com/v6/latest/CNY");
      if (!res.ok) throw new Error("API error");
      const data = await res.json();
      if (data.result === "success" && data.rates?.RUB) {
        setLiveRate(parseFloat(data.rates.RUB.toFixed(2)));
        // USD→RUB = RUB_per_CNY / USD_per_CNY
        if (data.rates?.USD) {
          const usdRub = data.rates.RUB / data.rates.USD;
          setLiveUsdRate(parseFloat(usdRub.toFixed(2)));
        }
        if (activate) setRateSource("live");
      }
    } catch (e) {
      if (activate) setRateSource("manual");
    } finally {
      setRateLoading(false);
    }
  }, []);

  useEffect(() => { fetchRate({ activate: false }); }, [fetchRate]);

  const effectiveRate = rateSource === "live" && liveRate ? liveRate : manualRate;
  const effectiveUsdRate = rateSource === "live" && liveUsdRate ? liveUsdRate : manualUsdRate;

  return { liveRate, liveUsdRate, effectiveRate, effectiveUsdRate, rateSource, rateLoading, fetchRate, setRateSource };
};

// --- 语言名称 & emoji ---
export const LANG_OPTIONS = [
  { code: "zh", label: "中文", flag: "🇨🇳" },
  { code: "en", label: "EN", flag: "🇬🇧" },
  { code: "ru", label: "РУ", flag: "🇷🇺" },
];
