// ============================================================
// 国际化 (i18n) + 货币格式化 + 实时汇率
// ============================================================
import { useState, useEffect, useCallback, createContext, useContext } from "react";

// --- 翻译字典 ---
const DICT = {
  // === Header ===
  brandSub: { zh: "Cross-border P&L · Россия 2026", en: "Cross-border P&L · Russia 2026", ru: "Кросс-бордер P&L · Россия 2026" },
  brandTitle: { zh: "俄罗斯电商损益与现金流计算器", en: "Russia E-commerce P&L Calculator", ru: "Калькулятор P&L для маркетплейсов" },
  saveCloud: { zh: "保存数据", en: "Save", ru: "Сохранить" },
  saving: { zh: "保存中…", en: "Saving…", ru: "Сохранение…" },
  exportCSV: { zh: "导出 CSV", en: "Export CSV", ru: "Экспорт CSV" },
  exportHTML: { zh: "导出报告", en: "Export Report", ru: "Экспорт отчёта" },
  htmlReportTitle: { zh: "俄罗斯电商投资效益分析报告", en: "Russia E-commerce P&L Analysis Report", ru: "Отчёт P&L для маркетплейсов" },
  htmlGenDate: { zh: "报告生成日期", en: "Report Generated", ru: "Дата отчёта" },
  htmlSummary: { zh: "总览摘要", en: "Executive Summary", ru: "Сводка" },
  htmlProductDetail: { zh: "商品明细", en: "Product Details", ru: "Детали товаров" },
  htmlCashFlow: { zh: "月度现金流明细", en: "Monthly Cash Flow Detail", ru: "Помесячный кэш" },
  htmlDisclaimer: { zh: "本报告由星哈酷投资效益分析系统自动生成，仅供测算参考，最终申报请咨询当地会计师。", en: "This report was auto-generated by XingHaKu Investment Analytics. For estimation only — consult a local accountant for filings.", ru: "Отчёт сгенерирован XingHaKu. Только для оценки — обратитесь к бухгалтеру." },
  htmlBreakEven: { zh: "回本月份", en: "Break-even Month", ru: "Месяц окупаемости" },
  htmlNoBreakEven: { zh: "预测期内未回本", en: "No break-even in forecast", ru: "Не окупается в прогнозе" },
  htmlTaxScheme: { zh: "税制方案", en: "Tax Scheme", ru: "Налоговый режим" },
  htmlExchangeRate: { zh: "汇率", en: "Exchange Rate", ru: "Курс" },
  htmlForecastPeriod: { zh: "预测期", en: "Forecast Period", ru: "Период прогноза" },
  resetSample: { zh: "重置样例", en: "Reset", ru: "Сброс" },
  saved: { zh: "✓ 已保存", en: "✓ Saved", ru: "✓ Сохранено" },
  saveFail: { zh: "保存失败", en: "Save failed", ru: "Ошибка сохранения" },
  loadedLocal: { zh: "已加载本地数据", en: "Local data loaded", ru: "Данные загружены" },
  shareLink: { zh: "分享链接", en: "Share Link", ru: "Поделиться" },
  shareCopied: { zh: "✓ 分享链接已复制到剪贴板", en: "✓ Share link copied to clipboard", ru: "✓ Ссылка скопирована" },
  shareFail: { zh: "生成分享链接失败", en: "Share link failed", ru: "Ошибка создания ссылки" },
  shareUploading: { zh: "⏳ 正在上传...", en: "⏳ Uploading...", ru: "⏳ Загрузка..." },
  loadedShare: { zh: "✓ 已从分享链接加载数据", en: "✓ Loaded from shared link", ru: "✓ Загружено из ссылки" },
  shareLoadFail: { zh: "分享链接数据加载失败", en: "Failed to load shared data", ru: "Ошибка загрузки из ссылки" },

  // === Tabs ===
  tabDashboard: { zh: "总览仪表盘", en: "Dashboard", ru: "Обзор" },
  tabProducts: { zh: "商品明细", en: "Products", ru: "Товары" },
  tabSchedule: { zh: "销售排期", en: "Sales Schedule", ru: "График продаж" },
  tabProjection: { zh: "现金流预测", en: "Cash Flow", ru: "Денежный поток" },
  tabSettings: { zh: "参数与税制", en: "Settings & Tax", ru: "Настройки" },
  tabHelp: { zh: "税制说明", en: "Tax Guide", ru: "Налоговый гид" },
  tabGlossary: { zh: "术语词典", en: "Glossary", ru: "Глоссарий" },

  // === Login ===
  loginTitle: { zh: "损益计算器", en: "P&L Calculator", ru: "Калькулятор P&L" },
  loginLabel: { zh: "访问密码", en: "Access Password", ru: "Пароль доступа" },
  loginPlaceholder: { zh: "请输入密码", en: "Enter password", ru: "Введите пароль" },
  loginButton: { zh: "进入系统", en: "Enter", ru: "Войти" },
  loginError: { zh: "密码错误，请重试", en: "Wrong password", ru: "Неверный пароль" },
  loginFooter: { zh: "星哈酷 · 投资效益分析工具", en: "XingHaKu · Investment Analytics", ru: "XingHaKu · Аналитика инвестиций" },

  // === Dashboard Metrics ===
  totalRevenue: { zh: "总营收", en: "Total Revenue", ru: "Общая выручка" },
  totalInvestment: { zh: "总投资", en: "Total Investment", ru: "Инвестиции" },
  russiaCollections: { zh: "俄罗斯回款", en: "Russia Collections", ru: "Поступления из РФ" },
  cashNetProfit: { zh: "现金净利", en: "Net Profit", ru: "Чистая прибыль" },
  projNetProfit: { zh: "预测净利润", en: "Projected Profit", ru: "Прогноз прибыли" },
  endingCash: { zh: "期末现金", en: "Ending Cash", ru: "Остаток на конец" },
  projMonthsRange: { zh: "预测 {n} 个月", en: "{n}-month forecast", ru: "Прогноз {n} мес." },
  roiLabel: { zh: "ROI / 投资回报", en: "ROI", ru: "ROI" },
  netMargin: { zh: "净利率", en: "Net Margin", ru: "Маржа" },
  bookNetProfit: { zh: "账面净利", en: "Book Net Profit", ru: "Бух. прибыль" },

  // === Dashboard Cards ===
  cumCashTitle: { zh: "累积现金流", en: "Cumulative Cash Flow", ru: "Накопленный кэш" },
  cumCashKicker: { zh: "Cumulative Cash", en: "Cumulative Cash", ru: "Кумулятивный кэш" },
  investorTitle: { zh: "投资人关注", en: "Investor Metrics", ru: "Метрики инвестора" },
  investorKicker: { zh: "Investor Metrics", en: "Investor Metrics", ru: "Инвестор" },
  initialOutflow: { zh: "初始投入", en: "Initial Outflow", ru: "Начальные вложения" },
  maxDrawdown: { zh: "最大资金压力", en: "Max Drawdown", ru: "Макс. просадка" },
  finalCash: { zh: "期末现金", en: "Final Cash", ru: "Итоговый кэш" },
  avgMonthly: { zh: "平均月回款", en: "Avg Monthly Revenue", ru: "Сред. месяц. выручка" },
  monthlyPnL: { zh: "月度净利分布", en: "Monthly P&L", ru: "Помесячная прибыль" },
  monthlyPnLKicker: { zh: "Monthly P&L", en: "Monthly P&L", ru: "Помесячно" },

  // === Break Even ===
  breakEvenMsg: { zh: "第 {n} 个月回本（达成盈亏平衡）", en: "Break even in month {n}", ru: "Окупаемость за {n} мес." },
  noBreakEven: { zh: "预测期内未回本，可调整销售排期或延长预测期", en: "No break-even within forecast period", ru: "Не окупается в прогнозном периоде" },

  // === Cost Structure ===
  costStructure: { zh: "成本结构", en: "Cost Structure", ru: "Структура затрат" },
  costKicker: { zh: "Cost Structure", en: "Cost Structure", ru: "Затраты" },
  costProcure: { zh: "采购+到俄运输", en: "Procurement + Shipping", ru: "Закупка + Доставка" },
  costPlatformFee: { zh: "平台费用", en: "Platform Fees", ru: "Комиссия площадки" },
  costWarehouse: { zh: "海外仓", en: "Warehouse", ru: "Склад" },
  costMgmt: { zh: "管理费", en: "Management", ru: "Управление" },
  costTax: { zh: "税", en: "Tax", ru: "Налоги" },
  costOneTime: { zh: "一次性费用", en: "One-time Costs", ru: "Разовые расходы" },
  costNetProfit: { zh: "净利润", en: "Net Profit", ru: "Чистая прибыль" },

  // === Tax Structure ===
  taxStructure: { zh: "税务结构", en: "Tax Breakdown", ru: "Структура налогов" },
  preTaxProfit: { zh: "税前利润", en: "Pre-tax Profit", ru: "Прибыль до налогов" },
  totalTax: { zh: "总税额", en: "Total Tax", ru: "Общий налог" },
  effectiveRate: { zh: "实际税负", en: "Effective Rate", ru: "Эффект. ставка" },

  // === Product Ranking ===
  rankingTitle: { zh: "商品盈利排行 (按ROI)", en: "Product Ranking (by ROI)", ru: "Рейтинг товаров (ROI)" },
  rankingKicker: { zh: "Profitability Ranking", en: "Profitability Ranking", ru: "Рейтинг" },

  // === Products Tab ===
  productsTitle: { zh: "商品明细", en: "Product Details", ru: "Детали товаров" },
  productCount: { zh: "{n} 个SKU", en: "{n} SKUs", ru: "{n} SKU" },
  productsHint: { zh: "点击行展开编辑（含申报价字段）。", en: "Click row to expand and edit.", ru: "Нажмите на строку для редактирования." },
  clearAll: { zh: "清空", en: "Clear", ru: "Очистить" },
  addProduct: { zh: "添加商品", en: "Add Product", ru: "Добавить" },
  productId: { zh: "产品ID", en: "Product ID", ru: "ID товара" },
  costCny: { zh: "实¥", en: "Cost ¥", ru: "Себест. ¥" },
  qty: { zh: "数量", en: "Qty", ru: "Кол-во" },
  listPrice: { zh: "售价₽", en: "List ₽", ru: "Цена ₽" },
  platformFee: { zh: "平台费", en: "Platform", ru: "Площадка" },
  warehouseFee: { zh: "仓费", en: "Storage", ru: "Склад" },
  mgmtFee: { zh: "管理", en: "Mgmt", ru: "Упр." },
  investment: { zh: "总投资", en: "Investment", ru: "Инвестиция" },
  revenue: { zh: "总营收", en: "Revenue", ru: "Выручка" },
  tax: { zh: "税", en: "Tax", ru: "Налог" },
  netProfitCol: { zh: "净利₽", en: "Profit", ru: "Прибыль" },
  roi: { zh: "ROI", en: "ROI", ru: "ROI" },
  action: { zh: "操作", en: "Action", ru: "Действие" },
  deleteBtn: { zh: "删除", en: "Delete", ru: "Удалить" },

  // === Schedule Tab ===
  scheduleTitle: { zh: "销售排期 · 按月预估销量", en: "Sales Schedule · Monthly Estimate", ru: "График продаж · Помесячно" },
  scheduleHint: { zh: "填入每个SKU每月预估销量。空白/零的列不会纳入费用。\"已分配\" 列会显示是否与备货量一致。", en: "Enter monthly estimated sales per SKU.", ru: "Введите плановые продажи по месяцам." },
  forecastMonths: { zh: "预测月数", en: "Forecast Months", ru: "Месяцев прогноза" },
  months: { zh: "个月", en: "months", ru: "мес." },
  filterSku: { zh: "一键匹配商品（输入匹配SKU）", en: "Filter SKUs", ru: "Фильтр SKU" },
  linearDist: { zh: "均匀平均", en: "Even", ru: "Равномерно" },
  frontload: { zh: "前重后轻", en: "Frontload", ru: "С начала" },
  bellCurve: { zh: "钟形曲线", en: "Bell Curve", ru: "Гаусс" },
  resetDist: { zh: "清空 (自动均分)", en: "Reset", ru: "Сброс" },
  sku: { zh: "SKU", en: "SKU", ru: "SKU" },
  total: { zh: "总量", en: "Total", ru: "Всего" },
  allocated: { zh: "已分配", en: "Allocated", ru: "Распред." },
  monthLabel: { zh: "M", en: "M", ru: "М" },

  // === Projection Tab ===
  projTitle: { zh: "现金流预测", en: "Cash Flow Forecast", ru: "Прогноз денежного потока" },
  currentMonth: { zh: "当前月份", en: "Current Month", ru: "Текущий месяц" },
  monthN: { zh: "第 {n} 月", en: "Month {n}", ru: "Месяц {n}" },
  maxInvestment: { zh: "最大资金占用", en: "Max Capital Required", ru: "Макс. вложения" },
  cashBalance: { zh: "最终净值", en: "Final Balance", ru: "Итоговый баланс" },
  totalProfit: { zh: "累计利润", en: "Total Profit", ru: "Общая прибыль" },
  vatThreshold: { zh: "VAT 触发阈值监控", en: "VAT Threshold Monitor", ru: "Мониторинг порога НДС" },
  vatAutoLabel: { zh: "营收过20M ₽自动触发VAT", en: "Auto-trigger VAT above 20M ₽", ru: "Авто НДС при выручке >20М ₽" },
  cumCashChart: { zh: "累积现金流（含投资支出）", en: "Cumulative Cash (incl. investment)", ru: "Накопленный кэш (с инвест.)" },
  monthlyNetProfit: { zh: "月度净利分布", en: "Monthly Net Profit", ru: "Помесячная прибыль" },
  projParams: { zh: "投测参数", en: "Projection Parameters", ru: "Параметры прогноза" },
  projMonths: { zh: "预测月数", en: "Forecast Months", ru: "Мес. прогноза" },
  partnerShare: { zh: "合伙人分润比例", en: "Partner Split Ratio", ru: "Доля партнёра" },
  withdrawalTitle: { zh: "分润排期 · 每月提取金额", en: "Withdrawal Schedule · Monthly Distribution", ru: "График распределения · Помесячно" },
  withdrawalHint: { zh: "每月填入你要提出来分润的金额（₽），0 = 不提取。提取金额不超过当月净利。", en: "Enter RUB amount to withdraw for distribution each month. 0 = no withdrawal. Capped at monthly net profit.", ru: "Введите сумму (₽) для распределения. 0 = без распределения. Не более месячной прибыли." },
  withdrawalLabel: { zh: "提取分润", en: "Withdrawal", ru: "Распределение" },
  withdrawalAmount: { zh: "提取金额 ₽", en: "Amount ₽", ru: "Сумма ₽" },
  resetWithdrawal: { zh: "重置分润", en: "Reset Withdrawal", ru: "Сброс распред." },
  withdrawalSplitNote: { zh: "提取金额按分润比例 {pct}% 分给合伙人，其余归你。未提取部分留在项目中。", en: "Withdrawn amount split {pct}% to partner. Remainder stays in project.", ru: "Распределяется {pct}% партнёру. Остаток — в проекте." },
  fixedCost: { zh: "每月固定支出（薪资/工具）", en: "Monthly Fixed Cost", ru: "Пост. расходы/мес." },
  priorRevenue: { zh: "本年已累计营收（跨阈值用）", en: "Prior Year Revenue", ru: "Выручка за пред. период" },
  projNote: { zh: "月测据：按预先每月的销量分配（默认从均匀排期计算），营业附加费（VAT）自动与跨档计算程序挂钩。", en: "Projection based on monthly sales schedule. VAT auto-escalation linked to revenue thresholds.", ru: "Прогноз по графику продаж. НДС привязан к порогам выручки." },
  cashFlowDetail: { zh: "月度损益与现金流明细", en: "Monthly P&L & Cash Flow Detail", ru: "Помесячный P&L и кэш" },
  cashFlowWarning: { zh: "\"损益现金\" vs \"现金流明细\"两个不同视角", en: "Two different views: P&L vs Cash Flow", ru: "Два ракурса: P&L и Кэш" },

  // === Table Headers (Projection) ===
  thMonth: { zh: "月份", en: "Month", ru: "Месяц" },
  thSoldQty: { zh: "售出", en: "Sold", ru: "Продано" },
  thRevenue: { zh: "销售回款", en: "Revenue", ru: "Выручка" },
  thCogs: { zh: "销货成本", en: "COGS", ru: "Себест." },
  thExpenses: { zh: "仓储佣金", en: "Expenses", ru: "Расходы" },
  thGrossProfit: { zh: "毛利/税前", en: "Gross Profit", ru: "Валовая" },
  thTax: { zh: "税", en: "Tax", ru: "Налог" },
  thNetProfit: { zh: "当月净利", en: "Net Profit", ru: "Чист. приб." },
  thPartner: { zh: "合伙人", en: "Partner", ru: "Партнёр" },
  thDistributed: { zh: "提取分润", en: "Distributed", ru: "Распред." },
  thOwner: { zh: "自己", en: "Owner", ru: "Владелец" },
  thCashFlow: { zh: "现金流", en: "Cash Flow", ru: "Кэш" },
  thCumCash: { zh: "累计现金", en: "Cum. Cash", ru: "Накоп. кэш" },
  thDamageLoss: { zh: "货损", en: "Damage", ru: "Потери" },
  initialRow: { zh: "初始（备货）", en: "Initial (Stock)", ru: "Начальные" },

  // === Settings Tab ===
  taxRegime: { zh: "俄罗斯税制选择", en: "Russian Tax Regime", ru: "Налоговый режим РФ" },
  taxRegimeKicker: { zh: "Tax Regime · 2026", en: "Tax Regime · 2026", ru: "Налоговый режим · 2026" },
  globalParams: { zh: "全局参数", en: "Global Parameters", ru: "Глобальные параметры" },
  globalParamsKicker: { zh: "Global Parameters", en: "Global Parameters", ru: "Параметры" },
  exchangeRate: { zh: "汇率（1元 → ? 卢布）", en: "Exchange Rate (1 CNY → ? RUB)", ru: "Курс (1 CNY → ? RUB)" },
  damageRate: { zh: "损耗率", en: "Damage Rate", ru: "Потери" },
  shippingPerUnit: { zh: "到俄运费/单品运费", en: "Shipping per Unit", ru: "Доставка за ед." },
  shippingMode: { zh: "清关方式", en: "Customs Mode", ru: "Режим таможни" },
  shippingManual: { zh: "手动输入", en: "Manual", ru: "Вручную" },
  shippingGray: { zh: "灰关（按重量）", en: "Gray (by weight)", ru: "Серая (вес)" },
  shippingWhite: { zh: "白关（按体积）", en: "White (by volume)", ru: "Белая (объём)" },
  grayShipPrice: { zh: "灰关运费单价", en: "Gray Customs Rate", ru: "Тариф серой" },
  whiteShipPrice: { zh: "白关运费单价", en: "White Customs Rate", ru: "Тариф белой" },
  weightKg: { zh: "单件重量", en: "Unit Weight", ru: "Вес ед." },
  volumeLWH: { zh: "单件体积 (长×宽×高)", en: "Unit Volume (L×W×H)", ru: "Объём (Д×Ш×В)" },
  volL: { zh: "长", en: "L", ru: "Д" },
  volW: { zh: "宽", en: "W", ru: "Ш" },
  volH: { zh: "高", en: "H", ru: "В" },
  calcShippingCost: { zh: "运费", en: "Shipping", ru: "Доставка" },
  grayNoVatNote: { zh: "⚠ 灰关无进项VAT发票，OSN下不可抵扣", en: "⚠ Gray customs: no import VAT invoice, non-deductible under OSN", ru: "⚠ Серая: нет вх. НДС, не вычитается при ОСН" },
  labelingCost: { zh: "贴标/标记 (Честный знак)", en: "Labeling (Chestny Znak)", ru: "Маркировка (Честный знак)" },
  oneTimeCosts: { zh: "首批一次性费用（设计/拍照/合规）", en: "One-time Setup Costs", ru: "Разовые расходы" },
  incomeBasis: { zh: "收入确认基础", en: "Income Recognition", ru: "Признание дохода" },
  incomeBasisKicker: { zh: "Income Recognition", en: "Income Recognition", ru: "Признание дохода" },
  basisPayout: { zh: "平台到手金额（M × 售价 − 平台费用）", en: "Platform Payout (M × Price − Fees)", ru: "Выплата площадки" },
  basisPayoutDesc: { zh: "实操推荐：以平台实际回款为税基入账。", en: "Recommended: use actual platform payout as tax base.", ru: "Рекомендуется: выплата площадки как налоговая база." },
  basisList: { zh: "全额上架价（M × 售价）", en: "Full List Price (M × Price)", ru: "Полная цена (М × Цена)" },
  basisListDesc: { zh: "最保守：把平台佣金大元加成入税, OSN 6% 下门槛会更高。", en: "Conservative: includes platform fees in tax base.", ru: "Консервативно: платформенные сборы в налоговую базу." },

  // === Footer ===
  footerText: { zh: "数据基于 联邦法 №425-FZ（2025.11.28，2026.1.1生效）。USN门槛 2026=20M / 2027=15M / 2028=10M ₽。", en: "Based on Federal Law №425-FZ (2025.11.28, effective 2026.1.1). USN thresholds: 2026=20M / 2027=15M / 2028=10M ₽.", ru: "По ФЗ №425-ФЗ (28.11.2025, с 01.01.2026). Пороги УСН: 2026=20М / 2027=15М / 2028=10М ₽." },
  footerDisclaimer: { zh: "本工具仅供测算参考，最终申报请咨询当地会计师。", en: "For estimation only. Consult a local accountant for filings.", ru: "Только для оценки. Обратитесь к бухгалтеру." },

  // === Exchange Rate ===
  liveRate: { zh: "实时汇率", en: "Live Rate", ru: "Курс онлайн" },
  rateUpdated: { zh: "汇率已更新", en: "Rate updated", ru: "Курс обновлён" },
  rateFailed: { zh: "汇率获取失败，使用手动值", en: "Rate fetch failed, using manual", ru: "Ошибка курса, ручной ввод" },
  rateManual: { zh: "手动", en: "Manual", ru: "Вручную" },
  rateLive: { zh: "实时", en: "Live", ru: "Онлайн" },

  // === Misc ===
  confirmClear: { zh: "确定清空所有商品？此操作不可撤销。", en: "Clear all products? This cannot be undone.", ru: "Очистить все товары? Это необратимо." },
  confirmReset: { zh: "重置为样例数据？当前编辑会丢失。", en: "Reset to sample data? Current edits will be lost.", ru: "Сбросить до примера? Текущие данные будут потеряны." },
  dualTrackNote: { zh: "在 USN 15% 或 OSN 下，税务局只认可有白关票据的\"报关申报\"成本。如果\"实际采购\"高于\"报关申报\"，差额部分将无法抵扣，会产生额外的税务损耗。", en: "Under USN 15% or OSN, only declared customs costs are deductible. If actual cost exceeds declared, the difference is non-deductible.", ru: "При УСН 15% или ОСН признаются только задекларированные таможенные расходы." },

  // === Charts ===
  chartBreakEven: { zh: "回本", en: "Break-even", ru: "Окупаемость" },
  chartCumCash: { zh: "累积现金", en: "Cum. Cash", ru: "Накоп. кэш" },
  chartMonthlyNet: { zh: "月度净利", en: "Monthly Net", ru: "Мес. прибыль" },

  // === Tax Breakdown Details ===
  inputVATLabel: { zh: "· 进项VAT（按申报价计提）", en: "· Input VAT (on declared value)", ru: "· Вх. НДС (по декларации)" },
  outputVATLabel: { zh: "· 销项VAT（向消费者收取）", en: "· Output VAT (charged to buyer)", ru: "· Исх. НДС (с покупателя)" },
  currentScheme: { zh: "当前方案：", en: "Current scheme: ", ru: "Текущая схема: " },

  // === Product Ranking / Table ===
  noProducts: { zh: "暂无商品。", en: "No products yet.", ru: "Товаров пока нет." },
  totalRow: { zh: "合计", en: "Total", ru: "Итого" },
  confirmDeleteProd: { zh: "删除 {id}？", en: "Delete {id}?", ru: "Удалить {id}?" },

  // === Product Editor ===
  editorFields: { zh: "编辑字段", en: "Edit Fields", ru: "Редактирование" },
  editorCalcDetail: { zh: "计算明细 / 单位", en: "Calc Details / Unit", ru: "Расчёт / Единица" },
  fieldProductId: { zh: "产品 ID", en: "Product ID", ru: "ID товара" },
  fieldActualCost: { zh: "实际采购价 (元)", en: "Actual Cost (CNY)", ru: "Факт. цена (CNY)" },
  fieldDeclaredCost: { zh: "申报/账面价 (元)", en: "Declared Cost (CNY)", ru: "Деклар. цена (CNY)" },
  fieldQty: { zh: "数量 (件)", en: "Quantity (pcs)", ru: "Кол-во (шт)" },
  fieldWeight: { zh: "重量 (kg)", en: "Weight (kg)", ru: "Вес (кг)" },
  fieldListPrice: { zh: "上架售价 (₽)", en: "List Price (₽)", ru: "Цена (₽)" },
  fieldPlatformFee: { zh: "平台费用 (₽/件)", en: "Platform Fee (₽/pc)", ru: "Комиссия (₽/шт)" },
  fieldWarehouse: { zh: "海外仓 (₽/件)", en: "Warehouse (₽/pc)", ru: "Склад (₽/шт)" },
  fieldMgmt: { zh: "管理费 (₽/件)", en: "Mgmt Fee (₽/pc)", ru: "Управление (₽/шт)" },
  vatBasisTag: { zh: "VAT基础", en: "VAT Base", ru: "База НДС" },
  calcActualRub: { zh: "实际卢布单价", en: "Actual RUB price", ru: "Факт. цена ₽" },
  calcDeclaredRub: { zh: "申报卢布单价", en: "Declared RUB price", ru: "Деклар. цена ₽" },
  calcShipping: { zh: "+ 到俄运费", en: "+ Shipping to RU", ru: "+ Доставка в РФ" },
  calcLabeling: { zh: "+ 诚实标签", en: "+ Labeling", ru: "+ Маркировка" },
  calcUnitCost: { zh: "= 实际单位成本", en: "= Unit Cost", ru: "= Себестоимость" },
  calcUnitPayout: { zh: "单位回款", en: "Unit Payout", ru: "Выплата/ед." },
  calcUnitGross: { zh: "单位毛利", en: "Unit Gross", ru: "Валовая/ед." },
  calcUnitNet: { zh: "单位净利", en: "Unit Net Profit", ru: "Чистая/ед." },
  calcInputVAT: { zh: "· 进项VAT/件", en: "· Input VAT/pc", ru: "· Вх. НДС/шт" },
  calcOutputVAT: { zh: "· 销项VAT/件", en: "· Output VAT/pc", ru: "· Исх. НДС/шт" },
  tagMargin: { zh: "净利率", en: "Margin", ru: "Маржа" },
  tagEffQty: { zh: "有效件数", en: "Eff. Qty", ru: "Эфф. кол-во" },

  // === VAT Threshold Monitor ===
  vatAutoTrigger: { zh: "营收过20M ₽自动触发VAT", en: "Auto-trigger VAT above 20M ₽", ru: "Авто НДС при выручке >20М ₽" },
  vatAutoDesc: { zh: "开启后，模型会跟踪你年度累计营收：", en: "When enabled, tracks annual cumulative revenue:", ru: "При включении отслеживается годовая выручка:" },
  vatTier0Desc: { zh: " 免VAT", en: " No VAT", ru: " Без НДС" },
  vatTier1Desc: { zh: " 自动加VAT 5%", en: " auto VAT 5%", ru: " авто НДС 5%" },
  vatTier2Desc: { zh: " VAT 7%", en: " VAT 7%", ru: " НДС 7%" },
  vatTier3Desc: { zh: " 强制 OSN（VAT 22% + 利润税）。", en: " mandatory OSN (VAT 22% + Profit Tax).", ru: " обязательно ОСН (НДС 22% + налог)." },
  vatFixedNote: { zh: "当前已固定为", en: "Currently fixed at", ru: "Зафиксировано:" },
  vatSwitchHint: { zh: "想看动态触发效果，请先在\"参数与税制\"切回 USN 6% 或 USN 15%。", en: "To see dynamic triggers, switch to USN 6% or 15% in Settings.", ru: "Для динамического НДС переключитесь на УСН 6% или 15%." },
  vatCumRevenue: { zh: "本年累计营收（含起始值）", en: "Annual Cumulative Revenue", ru: "Годовая выручка (накоп.)" },
  vatTagNoVat: { zh: "免VAT 0–20M", en: "No VAT 0–20M", ru: "Без НДС 0–20М" },
  vatTag5: { zh: "VAT 5% 20M–250M", en: "VAT 5% 20M–250M", ru: "НДС 5% 20М–250М" },
  vatTag7: { zh: "VAT 7% 250M–450M", en: "VAT 7% 250M–450M", ru: "НДС 7% 250М–450М" },
  vatTagOsn: { zh: "OSN 22% >450M", en: "OSN 22% >450M", ru: "ОСН 22% >450М" },
  vatTriggeredTitle: { zh: "第 {n} 个月起触发 VAT", en: "VAT triggered from month {n}", ru: "НДС с {n}-го месяца" },
  vatTriggeredDesc1: { zh: "累计营收在 M{n} 突破 20M ₽，从该月起自动加 VAT 5%。", en: "Cumulative revenue exceeded 20M ₽ in M{n}, auto VAT 5% applied.", ru: "Выручка превысила 20М ₽ в M{n}, авто НДС 5%." },
  vatTriggeredDesc2: { zh: "如果到下一年度，本年累计会重置 — 但若全年都超过门槛，下一整年都需要继续缴 VAT。", en: "Annual reset applies, but if threshold exceeded all year, VAT continues next year.", ru: "Годовой сброс, но при превышении весь год НДС продолжается." },
  vatTriggeredTotal: { zh: "总计 VAT 缴纳：", en: "Total VAT paid: ", ru: "Итого НДС: " },
  vatNotTriggered: { zh: "预测期内未触发 VAT", en: "VAT not triggered in forecast", ru: "НДС не активирован в прогнозе" },
  vatDistanceHint: { zh: "离 20M 阈值还有 {amount}。如果要扩大销售规模，可以延长预测期或提高月销量看看在第几个月会被触发。", en: "{amount} remaining to 20M threshold. Extend forecast or increase sales to see when VAT triggers.", ru: "До порога 20М осталось {amount}. Увеличьте прогноз или объём продаж." },

  // === Projection Detail Table ===
  projTaxNote: { zh: "月度税：每月按当月利润现算（实际USN为季度申报，OSN月度VAT；这里按月分摊以便观察）。", en: "Monthly tax calculated per month (actual STS is quarterly, GTS monthly VAT; shown monthly for analysis).", ru: "Помесячный налог (фактически УСН поквартально, ОСН помесячно НДС; показано помесячно)." },
  projInputVATNote: { zh: "进项VAT余额随月度销项VAT滚动抵扣；", en: "Input VAT credit rolls over monthly; ", ru: "Вх. НДС зачитывается помесячно; " },
  projInputVATLeft: { zh: "期末仍有 {amount} 未用完", en: "{amount} remaining unused", ru: "осталось {amount}" },
  projInputVATUsed: { zh: "已用完", en: "fully used", ru: "полностью использовано" },
  projCashVsPnl: { zh: "\"当月净利\" vs \"现金流\"两个不同视角：", en: "\"Net Profit\" vs \"Cash Flow\" — two views:", ru: "\"Чист. прибыль\" vs \"Кэш\" — два ракурса:" },
  projNetLabel: { zh: "当月净利", en: "Net Profit", ru: "Чист. прибыль" },
  projNetDesc: { zh: "= 营收 − 销货成本 − 仓+管理 − 税（会计利润，反映该月经营成果）", en: "= Revenue − COGS − WH+Mgmt − Tax (accounting profit)", ru: "= Выручка − Себест. − Склад+Упр. − Налог (бух. прибыль)" },
  projCashLabel: { zh: "现金流", en: "Cash Flow", ru: "Кэш" },
  projCashDesc: { zh: "= 营收 − 仓+管理 − 税 − 合伙人分成（M0已付全部库存款，月度不再扣销货成本，避免重复计算）", en: "= Revenue − WH+Mgmt − Tax − Partner (M0 paid all inventory, no monthly COGS)", ru: "= Выручка − Склад+Упр. − Налог − Партнёр (M0 оплачен весь запас)" },
  thTaxTier: { zh: "税档", en: "Tax Tier", ru: "Режим" },
  thSoldQtyD: { zh: "销售件数", en: "Units Sold", ru: "Продано" },
  thRevenueD: { zh: "营收", en: "Revenue", ru: "Выручка" },
  thCogsD: { zh: "销货成本", en: "COGS", ru: "Себест." },
  thWhMgmt: { zh: "仓+管理", en: "WH+Mgmt", ru: "Склад+Упр." },
  thFixedCost: { zh: "固定支出", en: "Fixed Cost", ru: "Пост. расх." },
  thMonthlyNet: { zh: "当月净利", en: "Net Profit", ru: "Чист. приб." },
  thCashFlowD: { zh: "现金流", en: "Cash Flow", ru: "Кэш" },
  thCumCashD: { zh: "累计现金", en: "Cum. Cash", ru: "Накоп. кэш" },
  investLabel: { zh: "(投资)", en: "(invest)", ru: "(инвест.)" },
  vatFixedSuffix: { zh: "(固定)", en: "(fixed)", ru: "(фикс.)" },
  // === VAT Tier Labels (cash flow table "税档" column) ===
  vatLabelNoVat: { zh: "免VAT", en: "No VAT", ru: "Без НДС" },
  vatLabelVat5: { zh: "VAT 5%", en: "VAT 5%", ru: "НДС 5%" },
  vatLabelVat7: { zh: "VAT 7%", en: "VAT 7%", ru: "НДС 7%" },
  vatLabelOsn22: { zh: "VAT 22% (OSN)", en: "VAT 22% (GTS)", ru: "НДС 22% (ОСН)" },
  vatLabelFixed5: { zh: "VAT 5% (固定)", en: "VAT 5% (fixed)", ru: "НДС 5% (фикс.)" },
  vatLabelFixed7: { zh: "VAT 7% (固定)", en: "VAT 7% (fixed)", ru: "НДС 7% (фикс.)" },
  vatLabelFixedOsn: { zh: "VAT {rate}% (固定)", en: "VAT {rate}% (fixed)", ru: "НДС {rate}% (фикс.)" },

  // === Tax Scheme Picker ===
  taxUsn6Label: { zh: "УСН 6%（按收入）", en: "STS 6% (on revenue)", ru: "УСН 6% (по доходам)" },
  taxUsn6Desc: { zh: "按全部收入征6%。营收 ≤ 20M₽ (2026) 免VAT。", en: "6% on all revenue. ≤ 20M₽ (2026) VAT-exempt.", ru: "6% от дохода. ≤ 20М₽ (2026) без НДС." },
  taxUsn15Label: { zh: "УСН 15%（收入−支出）", en: "STS 15% (revenue−expenses)", ru: "УСН 15% (доходы−расходы)" },
  taxUsn15Desc: { zh: "(收入−支出) × 15%，最低 1% × 收入。营收 ≤ 20M₽ 免VAT。", en: "(Revenue−Expenses) × 15%, min 1% × revenue. ≤ 20M₽ VAT-exempt.", ru: "(Доход−Расход) × 15%, мин. 1% × доход. ≤ 20М₽ без НДС." },
  taxUsn6v5Label: { zh: "УСН 6% + VAT 5%（无进项抵扣）", en: "STS 6% + VAT 5% (no input credit)", ru: "УСН 6% + НДС 5% (без вх. вычета)" },
  taxUsn6v5Desc: { zh: "营收 20–250M₽ 适用。收入 × 6% + VAT 5%，不可抵扣进项。", en: "Revenue 20–250M₽. Revenue × 6% + VAT 5%, no input credit.", ru: "Выручка 20–250М₽. Доход × 6% + НДС 5% без вычета." },
  taxUsn6v7Label: { zh: "УСН 6% + VAT 7%（无进项抵扣）", en: "STS 6% + VAT 7% (no input credit)", ru: "УСН 6% + НДС 7% (без вх. вычета)" },
  taxUsn6v7Desc: { zh: "营收 250–450M₽ 适用。收入 × 6% + VAT 7%，不可抵扣进项。", en: "Revenue 250–450M₽. Revenue × 6% + VAT 7%, no input credit.", ru: "Выручка 250–450М₽. Доход × 6% + НДС 7% без вычета." },
  taxUsn15v5Label: { zh: "УСН 15% + VAT 5%（无进项抵扣）", en: "STS 15% + VAT 5% (no input credit)", ru: "УСН 15% + НДС 5% (без вх. вычета)" },
  taxUsn15v5Desc: { zh: "营收 20–250M₽ 适用。VAT 5% 不可抵扣进项。", en: "Revenue 20–250M₽. VAT 5% without input credit.", ru: "Выручка 20–250М₽. НДС 5% без вх. вычета." },
  taxUsn15v7Label: { zh: "УСН 15% + VAT 7%（无进项抵扣）", en: "STS 15% + VAT 7% (no input credit)", ru: "УСН 15% + НДС 7% (без вх. вычета)" },
  taxUsn15v7Desc: { zh: "营收 250–450M₽ 适用。VAT 7% 不可抵扣进项。", en: "Revenue 250–450M₽. VAT 7% without input credit.", ru: "Выручка 250–450М₽. НДС 7% без вх. вычета." },
  taxOsnLabel: { zh: "ОСН（VAT 22% + 利润税 25%）", en: "GTS (VAT 22% + Profit Tax 25%)", ru: "ОСН (НДС 22% + налог на прибыль 25%)" },
  taxOsnDesc: { zh: "2026年VAT 20→22%，可用申报价进项VAT抵扣。利润税 25%。", en: "2026 VAT 20→22%, input VAT deductible. Profit tax 25%.", ru: "2026 НДС 20→22%, вх. НДС вычитается. Налог на прибыль 25%." },
  taxCustomLabel: { zh: "自定义税率", en: "Custom Tax Rate", ru: "Своя ставка" },
  taxCustomDesc: { zh: "按税前利润 × 自定义税率。", en: "Pre-tax profit × custom rate.", ru: "Прибыль до налогов × своя ставка." },
  customTaxRateLabel: { zh: "自定义税率（按税前利润）", en: "Custom Rate (on pre-tax profit)", ru: "Своя ставка (от прибыли)" },
  vatRateLabel: { zh: "VAT率 (2026: 22%)", en: "VAT Rate (2026: 22%)", ru: "Ставка НДС (2026: 22%)" },
  profitTaxLabel: { zh: "利润税率 (默认 25%)", en: "Profit Tax Rate (default 25%)", ru: "Налог на прибыль (25%)" },
  osnNote: { zh: "OSN下，每个SKU可单独填\"申报价(元)\"。进项VAT = 申报价 × 汇率 × 数量 × 22%（导入时支付），可滚动抵扣月度销项VAT。", en: "Under GTS, each SKU can have a \"Declared Cost\". Input VAT = Declared × Rate × Qty × 22% (paid at import), rolled over monthly.", ru: "При ОСН для каждого SKU можно указать \"деклар. цену\". Вх. НДС = Деклар. × Курс × Кол-во × 22%, зачитывается помесячно." },

  // === Params Panel ===
  paramExchangeRate: { zh: "汇率（1元 ≈ ? 卢布）", en: "Exchange Rate (1 CNY ≈ ? RUB)", ru: "Курс (1 CNY ≈ ? RUB)" },
  paramUsdRate: { zh: "美元汇率（1$ ≈ ? 卢布）", en: "USD Rate (1 USD ≈ ? RUB)", ru: "Курс USD (1 $ ≈ ? RUB)" },
  paramDamageRate: { zh: "货损率", en: "Damage Rate", ru: "Процент потерь" },
  paramShipping: { zh: "到俄罗斯单件运费", en: "Shipping per Unit to Russia", ru: "Доставка за ед. в Россию" },
  paramLabeling: { zh: "诚实标签 (Честный знак)", en: "Labeling (Chestny Znak)", ru: "Маркировка (Честный знак)" },
  paramOneTime: { zh: "首批一次性费用 (设计/拍照/合规)", en: "One-time Costs (design/photo/compliance)", ru: "Разовые расходы (дизайн/фото/серт.)" },

  // === Price Schedule ===
  priceScheduleTitle: { zh: "售价排期 · 按月调价", en: "Price Schedule · Monthly Pricing", ru: "График цен · Помесячно" },
  priceScheduleHint: { zh: "默认继承商品统一售价，修改后变色显示。空白/0 = 使用默认值。", en: "Defaults to product base price. Modified values shown in color. Empty/0 = default.", ru: "По умолчанию базовая цена. Изменённые выделены цветом. Пусто/0 = по умолчанию." },
  feeScheduleTitle: { zh: "平台费排期 · 按月调整", en: "Fee Schedule · Monthly Fees", ru: "График комиссий · Помесячно" },
  feeScheduleHint: { zh: "默认继承商品统一平台费。", en: "Defaults to product base platform fee.", ru: "По умолчанию базовая комиссия." },
  defaultPrice: { zh: "默认", en: "Default", ru: "По умолч." },
  resetPrices: { zh: "重置售价", en: "Reset Prices", ru: "Сброс цен" },
  resetFees: { zh: "重置平台费", en: "Reset Fees", ru: "Сброс комиссий" },
  priceLabel: { zh: "售价₽", en: "Price₽", ru: "Цена₽" },
  feeLabel: { zh: "平台费₽", en: "Fee₽", ru: "Комиссия₽" },

  // === Restock Schedule ===
  restockTitle: { zh: "补货排期 · 分批采购", en: "Restock Schedule · Batch Purchasing", ru: "График закупок · Партиями" },
  restockHint: { zh: "M0为首批采购，后续月份填入补货数量。0 = 不补货。", en: "M0 = initial batch. Fill restock qty for later months. 0 = no restock.", ru: "M0 = первая партия. Заполните кол-во для закупок. 0 = без закупки." },
  initialBatch: { zh: "首批(M0)", en: "Initial(M0)", ru: "Первая(M0)" },
  totalPurchased: { zh: "总采购", en: "Total Purchased", ru: "Всего закуплено" },
  resetRestock: { zh: "重置补货", en: "Reset Restock", ru: "Сброс закупок" },
  colRestock: { zh: "补货", en: "Restock", ru: "Закупка" },
  colStock: { zh: "库存", en: "Stock", ru: "Остаток" },
  stockWarning: { zh: "缺货", en: "Out of stock", ru: "Нехватка" },
  restockCostLabel: { zh: "补货支出", en: "Restock Cost", ru: "Расход на закупку" },
  cumPurchase: { zh: "累计采购", en: "Cum. Purchase", ru: "Накоп. закупка" },

  // === Help Panel ===
  helpTitle: { zh: "2026年俄罗斯税制要点", en: "2026 Russian Tax Reform", ru: "Налоговая реформа РФ 2026" },
  helpPractical: { zh: "跨境电商实务", en: "Cross-border E-commerce Tips", ru: "Практика кросс-бордер" },
  helpVatTitle: { zh: "VAT 标准税率：20% → 22%", en: "VAT Standard Rate: 20% → 22%", ru: "Ставка НДС: 20% → 22%" },
  helpVatDesc: { zh: "联邦法 №425-FZ（2025.11.28），2026.1.1起VAT基础税率上调至22%。食品、儿童用品、药品保留10%。", en: "Federal Law №425-FZ (2025.11.28), VAT raised to 22% from 2026.1.1. Food, children's, medicine remain 10%.", ru: "ФЗ №425-ФЗ (28.11.2025), НДС до 22% с 01.01.2026. Продукты, детские, лекарства — 10%." },
  helpUsnTitle: { zh: "USN 触发VAT门槛大幅下调", en: "STS VAT Threshold Lowered", ru: "Пороги НДС при УСН снижены" },
  helpUsnDesc: { zh: "超过门槛后可选：5%（20–250M）/ 7%（250–450M）无进项抵扣，或标准 0%/10%/22% 可抵扣。", en: "Above threshold: 5% (20–250M) / 7% (250–450M) no input credit, or standard 0%/10%/22% with credit.", ru: "Выше порога: 5% (20–250М) / 7% (250–450М) без вычета, или 0%/10%/22% с вычетом." },
  helpUsnBaseTitle: { zh: "USN 基本税率不变", en: "STS Base Rates Unchanged", ru: "Базовые ставки УСН без изменений" },
  helpUsnBaseDesc: { zh: "6%（按收入）和15%（按收入−支出）保持不变。USN 15%最低税额为收入1%。", en: "6% (on revenue) and 15% (revenue−expenses) unchanged. Min tax 1% of revenue.", ru: "6% и 15% без изменений. Мин. налог 1% дохода." },
  helpProfitTitle: { zh: "利润税：25%（OSN）", en: "Profit Tax: 25% (GTS)", ru: "Налог на прибыль: 25% (ОСН)" },
  helpProfitDesc: { zh: "2025起从20%上调。IT企业有5%优惠（至2030）。", en: "Raised from 20% since 2025. IT companies 5% (until 2030).", ru: "Повышен с 20% с 2025. IT — 5% (до 2030)." },
  helpVat22Title: { zh: "22% 是什么税？", en: "What is the 22% tax?", ru: "Что за налог 22%?" },
  helpVat22Desc: { zh: "2026年最常对应：① 新VAT基础税率；② NDFL（个税）最高累进档（年收入>50M ₽）。计算器把22%按VAT处理。", en: "In 2026: ① New VAT base rate; ② NDFL top bracket (>50M ₽/yr). Calculator treats 22% as VAT.", ru: "В 2026: ① Новая ставка НДС; ② НДФЛ макс. (>50М ₽/год). Калькулятор — 22% как НДС." },
  helpDeclaredTitle: { zh: "📦 申报价 vs 实际价", en: "📦 Declared vs Actual Cost", ru: "📦 Деклар. vs Факт. цена" },
  helpDeclaredDesc: { zh: "报关申报价决定进项VAT和关税基础。OSN下用申报价计算可抵扣的进项VAT。\"现金净利\"用实际成本，\"账面净利\"用申报成本，OSN下两者会有差异。", en: "Customs declared value determines input VAT and duty base. \"Cash Profit\" uses actual cost, \"Book Profit\" uses declared — differs under GTS.", ru: "Деклар. цена определяет вх. НДС. \"Кэш прибыль\" по факт., \"Бух. прибыль\" по деклар. — при ОСН различаются." },
  helpThresholdTitle: { zh: "⚠️ 营收逼近20M的策略", en: "⚠️ Near 20M Threshold Strategy", ru: "⚠️ Стратегия при 20М" },
  helpThresholdDesc: { zh: "① 拆分两个法人保持小规模；② 主动过线选5%/7%。5%无进项抵扣，但若你本来进项VAT就少，5%可能比15%标准USN更划算。", en: "① Split into two entities; ② Cross threshold, choose 5%/7%. If input VAT is small, 5% may beat standard 15%.", ru: "① Разделить на два юрлица; ② Перейти порог, выбрать 5%/7%. Если вх. НДС мал, 5% может быть выгоднее." },
  helpUsn6v15Title: { zh: "💰 USN 6% vs 15% 经验法则", en: "💰 STS 6% vs 15% Rule of Thumb", ru: "💰 УСН 6% vs 15% правило" },
  helpUsn6v15Desc: { zh: "可证明支出 > 收入60% → 选15%；否则选6%。跨境电商通常采购+物流+平台费占比高，多数情况15%更优。", en: "Provable expenses > 60% of revenue → choose 15%; otherwise 6%. Cross-border e-com usually has high costs, so 15% often wins.", ru: "Расходы > 60% дохода → 15%; иначе 6%. Кросс-бордер обычно с высокими расходами, 15% чаще выгоднее." },
  helpDamageTitle: { zh: "📊 货损双计修正", en: "📊 Damage Double-Count Fix", ru: "📊 Исправление двойного учёта потерь" },
  helpDamageDesc: { zh: "原表\"货损\"被重复扣除。本计算器仅通过减少有效销量(97%)体现货损，不再额外重复扣减。", en: "Original sheet double-counted damage. This calculator only reduces effective qty (97%), no extra deduction.", ru: "В оригинале потери считались дважды. Калькулятор уменьшает эфф. кол-во (97%), без доп. вычета." },
};

// --- 创建翻译函数 ---
export const createT = (lang) => (key, params) => {
  const entry = DICT[key];
  if (!entry) return key;
  let text = entry[lang] || entry.zh || key;
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, v);
    });
  }
  return text;
};

// --- 货币格式化工厂 ---
// exchangeRate = CNY→RUB,  usdRate = USD→RUB
export const createCurrencyFormatter = (lang, exchangeRate, usdRate = 95) => {

  const fmtRub = (v, digits = 0) => "₽ " + (Number(v) || 0).toLocaleString("ru-RU", { minimumFractionDigits: digits, maximumFractionDigits: digits });

  const fmtRubShort = (v) => {
    const n = Number(v) || 0;
    if (Math.abs(n) >= 1e6) return "₽" + (n / 1e6).toFixed(2) + "M";
    if (Math.abs(n) >= 1e3) return "₽" + (n / 1e3).toFixed(0) + "K";
    return "₽" + n.toFixed(0);
  };

  const fmtCny = (v) => "¥ " + (Number(v) || 0).toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const fmtCnyShort = (v) => {
    const n = Number(v) || 0;
    if (Math.abs(n) >= 1e6) return "¥" + (n / 1e6).toFixed(2) + "M";
    if (Math.abs(n) >= 1e4) return "¥" + (n / 1e4).toFixed(1) + "万";
    return "¥" + n.toFixed(0);
  };

  const fmtUsd = (v) => "$ " + (Number(v) || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  const fmtUsdShort = (v) => {
    const n = Number(v) || 0;
    if (Math.abs(n) >= 1e6) return "$" + (n / 1e6).toFixed(2) + "M";
    if (Math.abs(n) >= 1e3) return "$" + (n / 1e3).toFixed(1) + "K";
    return "$" + n.toFixed(0);
  };

  const fmtPct = (v) => ((Number(v) || 0) * 100).toFixed(1) + "%";

  // 主显示金额（zh=¥, en=$, ru=₽）
  const fmtPrimary = (rubValue) => {
    if (lang === "zh") return fmtCnyShort(rubValue / exchangeRate);
    if (lang === "en") return fmtUsdShort(rubValue / usdRate);
    return fmtRubShort(rubValue);
  };

  // 主显示金额（完整精度，用于表格明细）
  const fmtPrimaryFull = (rubValue, digits = 0) => {
    if (lang === "zh") return fmtCny(rubValue / exchangeRate);
    if (lang === "en") return fmtUsd(rubValue / usdRate);
    return fmtRub(rubValue, digits);
  };

  // 辅显示金额（小字副信息：显示 ₽ 原始值）
  const fmtSecondary = (rubValue) => {
    return fmtRubShort(rubValue);
  };

  return { fmtRub, fmtRubShort, fmtCny, fmtCnyShort, fmtUsd, fmtUsdShort, fmtPct, fmtPrimary, fmtPrimaryFull, fmtSecondary };
};

// --- 实时汇率 Hook ---
export const useLiveRate = (manualRate, manualUsdRate = 95) => {
  const [liveRate, setLiveRate] = useState(null);       // CNY→RUB
  const [liveUsdRate, setLiveUsdRate] = useState(null);  // USD→RUB
  const [rateSource, setRateSource] = useState("manual"); // "manual" | "live"
  const [rateLoading, setRateLoading] = useState(false);

  const fetchRate = useCallback(async () => {
    setRateLoading(true);
    try {
      const res = await fetch("https://open.er-api.com/v6/latest/CNY");
      if (!res.ok) throw new Error("API error");
      const data = await res.json();
      if (data.result === "success" && data.rates?.RUB) {
        setLiveRate(parseFloat(data.rates.RUB.toFixed(2)));
        // USD→RUB = RUB_per_CNY / USD_per_CNY
        if (data.rates?.USD) {
          const usdRub = data.rates.RUB / data.rates.USD;
          setLiveUsdRate(parseFloat(usdRub.toFixed(2)));
        }
        setRateSource("live");
      }
    } catch (e) {
      setRateSource("manual");
    } finally {
      setRateLoading(false);
    }
  }, []);

  useEffect(() => { fetchRate(); }, [fetchRate]);

  const effectiveRate = rateSource === "live" && liveRate ? liveRate : manualRate;
  const effectiveUsdRate = rateSource === "live" && liveUsdRate ? liveUsdRate : manualUsdRate;

  return { liveRate, liveUsdRate, effectiveRate, effectiveUsdRate, rateSource, rateLoading, fetchRate, setRateSource };
};

// --- 语言名称 & emoji ---
export const LANG_OPTIONS = [
  { code: "zh", label: "中文", flag: "🇨🇳" },
  { code: "en", label: "EN", flag: "🇬🇧" },
  { code: "ru", label: "РУ", flag: "🇷🇺" },
];
